// Code generated by box-gantry. DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"crypto/sha1"
	"encoding/base64"
	"fmt"
	"sync"

	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// ChunkedUpload orchestrates a Box chunked (multipart) upload over a Client: it
// creates an upload session, uploads the content's parts in parallel, and
// commits — for a new file (Upload) or a new version of an existing file
// (UploadVersion). Box requires chunked upload for files at or above its
// minimum session size; smaller files use the single-shot upload endpoints.
type ChunkedUpload struct {
	client *Client
	// maxConcurrent bounds parts in flight, capping peak buffer memory.
	maxConcurrent int
}

// NewChunkedUpload builds an orchestrator over an existing client.
func (c *Client) NewChunkedUpload() *ChunkedUpload {
	return &ChunkedUpload{client: c, maxConcurrent: 4}
}

// Upload uploads content as a new file named fileName into folderID.
func (u *ChunkedUpload) Upload(ctx context.Context, content []byte, fileName, folderID string) (*schemas.Files, error) {
	session, err := u.client.ChunkedUploads.CreateFileUploadSession(ctx, &schemas.FileUploadSessionCreateRequest{
		FolderId: folderID,
		FileSize: int64(len(content)),
		FileName: fileName,
	})
	if err != nil {
		return nil, err
	}
	return u.finish(ctx, session, content)
}

// UploadVersion uploads content as a new version of the existing file fileID.
func (u *ChunkedUpload) UploadVersion(ctx context.Context, content []byte, fileName, fileID string) (*schemas.Files, error) {
	session, err := u.client.ChunkedUploads.CreateFileVersionUploadSession(ctx, fileID, &schemas.FileVersionUploadSessionCreateRequest{
		FileSize: int64(len(content)),
		FileName: &fileName,
	})
	if err != nil {
		return nil, err
	}
	return u.finish(ctx, session, content)
}

func (u *ChunkedUpload) finish(ctx context.Context, session *schemas.UploadSession, content []byte) (*schemas.Files, error) {
	if session.Id == nil {
		return nil, fmt.Errorf("gantry: upload session returned no id")
	}
	if session.PartSize == nil || *session.PartSize <= 0 {
		return nil, fmt.Errorf("gantry: upload session returned a non-positive part_size")
	}
	id := *session.Id
	partSize := int(*session.PartSize)
	total := len(content)

	var offsets []int
	for off := 0; off < total; off += partSize {
		offsets = append(offsets, off)
	}
	parts := make([]schemas.UploadPart, len(offsets))

	// Cancel the still-queued and in-flight part uploads as soon as one fails,
	// so a failure early in a large upload doesn't push every remaining part.
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	sem := make(chan struct{}, u.maxConcurrent)
	var wg sync.WaitGroup
	var mu sync.Mutex
	var firstErr error
	for i, off := range offsets {
		wg.Add(1)
		sem <- struct{}{}
		go func(i, off int) {
			defer wg.Done()
			defer func() { <-sem }()
			end := off + partSize
			if end > total {
				end = total
			}
			part, err := u.uploadPart(ctx, id, content, off, end, total)
			mu.Lock()
			defer mu.Unlock()
			if err != nil {
				if firstErr == nil {
					firstErr = err
					cancel()
				}
				return
			}
			parts[i] = part
		}(i, off)
	}
	wg.Wait()
	if firstErr != nil {
		return nil, firstErr
	}

	digest := "sha=" + base64.StdEncoding.EncodeToString(sha1sum(content))
	return u.client.ChunkedUploads.CommitFileUploadSession(ctx, id, digest, &schemas.FileUploadSessionCommitRequest{Parts: parts}, nil)
}

func (u *ChunkedUpload) uploadPart(ctx context.Context, id string, content []byte, start, end, total int) (schemas.UploadPart, error) {
	slice := content[start:end]
	digest := "sha=" + base64.StdEncoding.EncodeToString(sha1sum(slice))
	contentRange := fmt.Sprintf("bytes %d-%d/%d", start, end-1, total)
	uploaded, err := u.client.ChunkedUploads.UpdateFileUploadSession(ctx, id, digest, contentRange, bytes.NewReader(slice))
	if err != nil {
		return schemas.UploadPart{}, err
	}
	if uploaded == nil || uploaded.Part == nil {
		return schemas.UploadPart{}, fmt.Errorf("gantry: upload part returned no part")
	}
	return *uploaded.Part, nil
}

func sha1sum(b []byte) []byte {
	sum := sha1.Sum(b)
	return sum[:]
}
