// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package client

import (
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/managers"
)

// Client is the single entry point: one field per resource manager.
type Client struct {
	Ai                                          *managers.AiManager
	AiStudio                                    *managers.AiStudioManager
	AppItemAssociations                         *managers.AppItemAssociationsManager
	Archives                                    *managers.ArchivesManager
	Authorization                               *managers.AuthorizationManager
	AutomateWorkflows                           *managers.AutomateWorkflowsManager
	Avatars                                     *managers.AvatarsManager
	ChunkedUploads                              *managers.ChunkedUploadsManager
	Classifications                             *managers.ClassificationsManager
	CollaborationAllowlistEntries               *managers.CollaborationAllowlistEntriesManager
	CollaborationAllowlistExemptTargets         *managers.CollaborationAllowlistExemptTargetsManager
	Collections                                 *managers.CollectionsManager
	Comments                                    *managers.CommentsManager
	DevicePinners                               *managers.DevicePinnersManager
	Docgen                                      *managers.DocgenManager
	DocgenTemplate                              *managers.DocgenTemplateManager
	Downloads                                   *managers.DownloadsManager
	EmailAliases                                *managers.EmailAliasesManager
	EnterpriseConfigurations                    *managers.EnterpriseConfigurationsManager
	Events                                      *managers.EventsManager
	ExternalUsers                               *managers.ExternalUsersManager
	FileClassifications                         *managers.FileClassificationsManager
	FileMetadata                                *managers.FileMetadataManager
	FileRequests                                *managers.FileRequestsManager
	FileVersionLegalHolds                       *managers.FileVersionLegalHoldsManager
	FileVersionRetentions                       *managers.FileVersionRetentionsManager
	FileVersions                                *managers.FileVersionsManager
	FileWatermarks                              *managers.FileWatermarksManager
	Files                                       *managers.FilesManager
	FolderClassifications                       *managers.FolderClassificationsManager
	FolderLocks                                 *managers.FolderLocksManager
	FolderMetadata                              *managers.FolderMetadataManager
	FolderWatermarks                            *managers.FolderWatermarksManager
	Folders                                     *managers.FoldersManager
	Groups                                      *managers.GroupsManager
	HubCollaborations                           *managers.HubCollaborationsManager
	HubDocument                                 *managers.HubDocumentManager
	HubItems                                    *managers.HubItemsManager
	Hubs                                        *managers.HubsManager
	IntegrationMappings                         *managers.IntegrationMappingsManager
	Invites                                     *managers.InvitesManager
	LegalHoldPolicies                           *managers.LegalHoldPoliciesManager
	LegalHoldPolicyAssignments                  *managers.LegalHoldPolicyAssignmentsManager
	ListCollaborations                          *managers.ListCollaborationsManager
	Memberships                                 *managers.MembershipsManager
	MetadataCascadePolicies                     *managers.MetadataCascadePoliciesManager
	MetadataTaxonomies                          *managers.MetadataTaxonomiesManager
	MetadataTemplates                           *managers.MetadataTemplatesManager
	Notes                                       *managers.NotesManager
	RecentItems                                 *managers.RecentItemsManager
	RetentionPolicies                           *managers.RetentionPoliciesManager
	RetentionPolicyAssignments                  *managers.RetentionPolicyAssignmentsManager
	Search                                      *managers.SearchManager
	SessionTermination                          *managers.SessionTerminationManager
	SharedLinksAppItems                         *managers.SharedLinksAppItemsManager
	SharedLinksFiles                            *managers.SharedLinksFilesManager
	SharedLinksFolders                          *managers.SharedLinksFoldersManager
	SharedLinksWebLinks                         *managers.SharedLinksWebLinksManager
	ShieldInformationBarrierReports             *managers.ShieldInformationBarrierReportsManager
	ShieldInformationBarrierSegmentMembers      *managers.ShieldInformationBarrierSegmentMembersManager
	ShieldInformationBarrierSegmentRestrictions *managers.ShieldInformationBarrierSegmentRestrictionsManager
	ShieldInformationBarrierSegments            *managers.ShieldInformationBarrierSegmentsManager
	ShieldInformationBarriers                   *managers.ShieldInformationBarriersManager
	ShieldLists                                 *managers.ShieldListsManager
	SignRequests                                *managers.SignRequestsManager
	SignTemplates                               *managers.SignTemplatesManager
	Skills                                      *managers.SkillsManager
	StoragePolicies                             *managers.StoragePoliciesManager
	StoragePolicyAssignments                    *managers.StoragePolicyAssignmentsManager
	TaskAssignments                             *managers.TaskAssignmentsManager
	Tasks                                       *managers.TasksManager
	TermsOfServiceUserStatuses                  *managers.TermsOfServiceUserStatusesManager
	TermsOfServices                             *managers.TermsOfServicesManager
	Transfer                                    *managers.TransferManager
	TrashedFiles                                *managers.TrashedFilesManager
	TrashedFolders                              *managers.TrashedFoldersManager
	TrashedItems                                *managers.TrashedItemsManager
	TrashedWebLinks                             *managers.TrashedWebLinksManager
	Uploads                                     *managers.UploadsManager
	UserCollaborations                          *managers.UserCollaborationsManager
	Users                                       *managers.UsersManager
	WebLinks                                    *managers.WebLinksManager
	Webhooks                                    *managers.WebhooksManager
	Workflows                                   *managers.WorkflowsManager
	ZipDownloads                                *managers.ZipDownloadsManager
}

// NewClient wires every manager to a runtime session built from the
// token source and options.
func NewClient(ts gantryruntime.TokenSource, opts ...gantryruntime.Option) *Client {
	session := gantryruntime.New(ts, opts...)
	c := &Client{}
	c.Ai = managers.NewAiManager(session)
	c.AiStudio = managers.NewAiStudioManager(session)
	c.AppItemAssociations = managers.NewAppItemAssociationsManager(session)
	c.Archives = managers.NewArchivesManager(session)
	c.Authorization = managers.NewAuthorizationManager(session)
	c.AutomateWorkflows = managers.NewAutomateWorkflowsManager(session)
	c.Avatars = managers.NewAvatarsManager(session)
	c.ChunkedUploads = managers.NewChunkedUploadsManager(session)
	c.Classifications = managers.NewClassificationsManager(session)
	c.CollaborationAllowlistEntries = managers.NewCollaborationAllowlistEntriesManager(session)
	c.CollaborationAllowlistExemptTargets = managers.NewCollaborationAllowlistExemptTargetsManager(session)
	c.Collections = managers.NewCollectionsManager(session)
	c.Comments = managers.NewCommentsManager(session)
	c.DevicePinners = managers.NewDevicePinnersManager(session)
	c.Docgen = managers.NewDocgenManager(session)
	c.DocgenTemplate = managers.NewDocgenTemplateManager(session)
	c.Downloads = managers.NewDownloadsManager(session)
	c.EmailAliases = managers.NewEmailAliasesManager(session)
	c.EnterpriseConfigurations = managers.NewEnterpriseConfigurationsManager(session)
	c.Events = managers.NewEventsManager(session)
	c.ExternalUsers = managers.NewExternalUsersManager(session)
	c.FileClassifications = managers.NewFileClassificationsManager(session)
	c.FileMetadata = managers.NewFileMetadataManager(session)
	c.FileRequests = managers.NewFileRequestsManager(session)
	c.FileVersionLegalHolds = managers.NewFileVersionLegalHoldsManager(session)
	c.FileVersionRetentions = managers.NewFileVersionRetentionsManager(session)
	c.FileVersions = managers.NewFileVersionsManager(session)
	c.FileWatermarks = managers.NewFileWatermarksManager(session)
	c.Files = managers.NewFilesManager(session)
	c.FolderClassifications = managers.NewFolderClassificationsManager(session)
	c.FolderLocks = managers.NewFolderLocksManager(session)
	c.FolderMetadata = managers.NewFolderMetadataManager(session)
	c.FolderWatermarks = managers.NewFolderWatermarksManager(session)
	c.Folders = managers.NewFoldersManager(session)
	c.Groups = managers.NewGroupsManager(session)
	c.HubCollaborations = managers.NewHubCollaborationsManager(session)
	c.HubDocument = managers.NewHubDocumentManager(session)
	c.HubItems = managers.NewHubItemsManager(session)
	c.Hubs = managers.NewHubsManager(session)
	c.IntegrationMappings = managers.NewIntegrationMappingsManager(session)
	c.Invites = managers.NewInvitesManager(session)
	c.LegalHoldPolicies = managers.NewLegalHoldPoliciesManager(session)
	c.LegalHoldPolicyAssignments = managers.NewLegalHoldPolicyAssignmentsManager(session)
	c.ListCollaborations = managers.NewListCollaborationsManager(session)
	c.Memberships = managers.NewMembershipsManager(session)
	c.MetadataCascadePolicies = managers.NewMetadataCascadePoliciesManager(session)
	c.MetadataTaxonomies = managers.NewMetadataTaxonomiesManager(session)
	c.MetadataTemplates = managers.NewMetadataTemplatesManager(session)
	c.Notes = managers.NewNotesManager(session)
	c.RecentItems = managers.NewRecentItemsManager(session)
	c.RetentionPolicies = managers.NewRetentionPoliciesManager(session)
	c.RetentionPolicyAssignments = managers.NewRetentionPolicyAssignmentsManager(session)
	c.Search = managers.NewSearchManager(session)
	c.SessionTermination = managers.NewSessionTerminationManager(session)
	c.SharedLinksAppItems = managers.NewSharedLinksAppItemsManager(session)
	c.SharedLinksFiles = managers.NewSharedLinksFilesManager(session)
	c.SharedLinksFolders = managers.NewSharedLinksFoldersManager(session)
	c.SharedLinksWebLinks = managers.NewSharedLinksWebLinksManager(session)
	c.ShieldInformationBarrierReports = managers.NewShieldInformationBarrierReportsManager(session)
	c.ShieldInformationBarrierSegmentMembers = managers.NewShieldInformationBarrierSegmentMembersManager(session)
	c.ShieldInformationBarrierSegmentRestrictions = managers.NewShieldInformationBarrierSegmentRestrictionsManager(session)
	c.ShieldInformationBarrierSegments = managers.NewShieldInformationBarrierSegmentsManager(session)
	c.ShieldInformationBarriers = managers.NewShieldInformationBarriersManager(session)
	c.ShieldLists = managers.NewShieldListsManager(session)
	c.SignRequests = managers.NewSignRequestsManager(session)
	c.SignTemplates = managers.NewSignTemplatesManager(session)
	c.Skills = managers.NewSkillsManager(session)
	c.StoragePolicies = managers.NewStoragePoliciesManager(session)
	c.StoragePolicyAssignments = managers.NewStoragePolicyAssignmentsManager(session)
	c.TaskAssignments = managers.NewTaskAssignmentsManager(session)
	c.Tasks = managers.NewTasksManager(session)
	c.TermsOfServiceUserStatuses = managers.NewTermsOfServiceUserStatusesManager(session)
	c.TermsOfServices = managers.NewTermsOfServicesManager(session)
	c.Transfer = managers.NewTransferManager(session)
	c.TrashedFiles = managers.NewTrashedFilesManager(session)
	c.TrashedFolders = managers.NewTrashedFoldersManager(session)
	c.TrashedItems = managers.NewTrashedItemsManager(session)
	c.TrashedWebLinks = managers.NewTrashedWebLinksManager(session)
	c.Uploads = managers.NewUploadsManager(session)
	c.UserCollaborations = managers.NewUserCollaborationsManager(session)
	c.Users = managers.NewUsersManager(session)
	c.WebLinks = managers.NewWebLinksManager(session)
	c.Webhooks = managers.NewWebhooksManager(session)
	c.Workflows = managers.NewWorkflowsManager(session)
	c.ZipDownloads = managers.NewZipDownloadsManager(session)
	return c
}
