// Code generated by box-gantry. DO NOT EDIT.

// Package boxopensdk is the module root for the Box Open SDK for Go: an open
// source, community-built client for the Box API, generated from the Box
// OpenAPI specification.
//
// This package is documentation only and exports nothing. The SDK lives in its
// subpackages:
//
//   - [github.com/unofficialbox/box-open-go-sdk/client] — the Client, one manager per API area.
//   - [github.com/unofficialbox/box-open-go-sdk/auth] — Client Credentials Grant, JWT, OAuth, developer token.
//   - [github.com/unofficialbox/box-open-go-sdk/schemas] — the typed request and response models.
//   - [github.com/unofficialbox/box-open-go-sdk/gantryruntime] — the net/http runtime: retry, backoff, token refresh.
//
// A first call:
//
//	c := client.NewClient(auth.ClientCredentials(auth.CCGConfig{
//		ClientID:     "CLIENT_ID",
//		ClientSecret: "CLIENT_SECRET",
//		EnterpriseID: "ENTERPRISE_ID",
//	}))
//	me, err := c.Users.GetMe(context.Background(), nil)
//
// See the README for an end-to-end Quickstart, and docs/ for a reference page
// per manager with an example on every method.
//
// Not affiliated with, authorized, or endorsed by Box, Inc. "Box" is a
// trademark of Box, Inc. This is an independent, generated client.
package boxopensdk
