// Code generated by box-gantry. DO NOT EDIT.
package serialization

import (
	"encoding/json"
	"testing"
)

type triState struct {
	Field *Nullable[string] `json:"field,omitempty"`
}

func TestNullableWriteTriState(t *testing.T) {
	// The tri-state is expressed on write (Box clear-on-update, BG-1):
	// absent omits the key, Null serializes null, Value serializes it.
	absent, err := json.Marshal(triState{})
	if err != nil {
		t.Fatal(err)
	}
	if string(absent) != "{}" {
		t.Fatalf("absent should omit the key, got %s", absent)
	}

	null, err := json.Marshal(triState{Field: Null[string]()})
	if err != nil {
		t.Fatal(err)
	}
	if string(null) != `{"field":null}` {
		t.Fatalf("null should serialize as null, got %s", null)
	}

	value, err := json.Marshal(triState{Field: Value("x")})
	if err != nil {
		t.Fatal(err)
	}
	if string(value) != `{"field":"x"}` {
		t.Fatalf("value should serialize the value, got %s", value)
	}
}

func TestNullableRead(t *testing.T) {
	// A present value round-trips to a valid Nullable.
	var back triState
	if err := json.Unmarshal([]byte(`{"field":"y"}`), &back); err != nil {
		t.Fatal(err)
	}
	if back.Field == nil || !back.Field.Valid || back.Field.Value != "y" {
		t.Fatalf("value should unmarshal to a valid Nullable with the value")
	}

	// A JSON null does not error. encoding/json collapses null to a nil
	// pointer for pointer fields (UnmarshalJSON is not called), so on read
	// null and absent both surface as nil — acceptable, since the
	// tri-state guarantee is a write-side one.
	back = triState{}
	if err := json.Unmarshal([]byte(`{"field":null}`), &back); err != nil {
		t.Fatal(err)
	}
	if back.Field != nil {
		t.Fatalf("read null should surface as nil (absent-equivalent), got %+v", back.Field)
	}
}

func TestDateRoundTrip(t *testing.T) {
	var d Date
	if err := json.Unmarshal([]byte(`"2026-07-12"`), &d); err != nil {
		t.Fatal(err)
	}
	if d.String() != "2026-07-12" {
		t.Fatalf("date parse: got %s", d.String())
	}
	out, err := json.Marshal(d)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != `"2026-07-12"` {
		t.Fatalf("date marshal: got %s", out)
	}
}
