// Code generated by box-gantry. DO NOT EDIT.
package serialization

import (
	"bytes"
	"encoding/json"
	"time"
)

// Nullable models the D-110 tri-state at a field that may be absent,
// explicitly null, or a value. Use *Nullable[T] with `,omitempty`: a nil
// pointer is absent; a non-nil pointer is sent, as null or as the value.
type Nullable[T any] struct {
	// Valid is false for an explicit JSON null.
	Valid bool
	Value T
}

// Value builds a present, non-null Nullable.
func Value[T any](v T) *Nullable[T] { return &Nullable[T]{Valid: true, Value: v} }

// Null builds a present, explicitly-null Nullable.
func Null[T any]() *Nullable[T] { return &Nullable[T]{} }

func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.Value)
}

func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		var zero T
		n.Valid, n.Value = false, zero
		return nil
	}
	n.Valid = true
	return json.Unmarshal(data, &n.Value)
}

// Date is an RFC 3339 full-date (no time component).
type Date struct{ time.Time }

const dateLayout = "2006-01-02"

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Time.Format(dateLayout))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	t, err := time.Parse(dateLayout, s)
	if err != nil {
		return err
	}
	d.Time = t
	return nil
}

func (d Date) String() string { return d.Time.Format(dateLayout) }
