// Code generated by gantry-contract — do not edit.
//
// Compilable stubs for the hand-written runtime surface (FR-5.3).
// Generated SDK code compile-verifies against this package; the
// real runtime implements the same contract.
package gantryruntime

import (
	"context"
	"io"
)

// Request is the runtime-owned HTTP request envelope.
type Request struct{ private struct{} }

// Response is the runtime-owned HTTP response envelope.
type Response struct{ private struct{} }

// TokenSource yields an access token for the configured auth flow.
type TokenSource interface {
	AccessToken(ctx context.Context) (string, error)
}

// Option configures a Client at construction (the With* surface).
type Option func(*Client)

// Client is the runtime session holding config (auth, base URLs,
// HTTP client, retry policy). Session-receiver contract functions
// are its methods.
type Client struct{ private struct{} }

// New builds a runtime Client for a token source and options.
func New(ts TokenSource, opts ...Option) *Client {
	panic("gantryruntime stub: New is not wired to a real runtime")
}

// Fetch — Execute the request with retries: exponential backoff + jitter, 401 token refresh, Retry-After handling (R§1 network layer).
func (c *Client) Fetch(ctx context.Context, request *Request) (*Response, error) {
	panic("gantryruntime stub: fetch is not wired to a real runtime")
}

// AccessToken — Return a valid access token for the configured auth flow, acquiring or refreshing through the pluggable token store as needed.
func (c *Client) AccessToken(ctx context.Context) (string, error) {
	panic("gantryruntime stub: access_token is not wired to a real runtime")
}

// BaseUrl — The configured base URL for a D-106 class ("api", "api_root", "upload", "upload_session", "oauth_authorize", "download"), without a trailing slash. Runtime configuration may override any of them (custom deployments).
func (c *Client) BaseUrl(name string) string {
	panic("gantryruntime stub: base_url is not wired to a real runtime")
}

// NewRequest — Create a request envelope for the given method and fully built URL.
func (c *Client) NewRequest(method string, url string) *Request {
	panic("gantryruntime stub: new_request is not wired to a real runtime")
}

// WithHeader — Return the request with the header set.
func WithHeader(request *Request, name string, value string) *Request {
	panic("gantryruntime stub: with_header is not wired to a real runtime")
}

// WithQuery — Return the request with the query parameter appended, encoded.
func WithQuery(request *Request, name string, value string) *Request {
	panic("gantryruntime stub: with_query is not wired to a real runtime")
}

// WithJsonBody — Return the request with the serialized JSON body and content type set.
func WithJsonBody(request *Request, body []byte) *Request {
	panic("gantryruntime stub: with_json_body is not wired to a real runtime")
}

// WithFormBody — Return the request with an application/x-www-form-urlencoded body (the OAuth2 token endpoints).
func WithFormBody(request *Request, form []byte) *Request {
	panic("gantryruntime stub: with_form_body is not wired to a real runtime")
}

// WithStreamBody — Return the request with a streaming body (buffered on platforms whose manifest says so — FR-7.4).
func WithStreamBody(request *Request, body io.Reader, contentType string) *Request {
	panic("gantryruntime stub: with_stream_body is not wired to a real runtime")
}

// WithMultipartBody — Return the request with a Box-style multipart body: an `attributes` JSON part plus a file part (G-7).
func WithMultipartBody(request *Request, attributes []byte, fileName string, file io.Reader) *Request {
	panic("gantryruntime stub: with_multipart_body is not wired to a real runtime")
}

// ResponseBytes — Read the whole response body.
func ResponseBytes(response *Response) ([]byte, error) {
	panic("gantryruntime stub: response_bytes is not wired to a real runtime")
}

// ResponseStream — The response body as a stream, for binary downloads (FR-7.4).
func ResponseStream(response *Response) io.Reader {
	panic("gantryruntime stub: response_stream is not wired to a real runtime")
}

// ResponseHeader — A response header value, empty when absent (redirect Location, Retry-After surfacing).
func ResponseHeader(response *Response, name string) string {
	panic("gantryruntime stub: response_header is not wired to a real runtime")
}

// StatusCode — The response status code.
func StatusCode(response *Response) int64 {
	panic("gantryruntime stub: status_code is not wired to a real runtime")
}
