// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// AiManager groups the "ai" operations.
type AiManager struct {
	session *gantryruntime.Client
}

// NewAiManager builds the manager against a runtime session.
func NewAiManager(session *gantryruntime.Client) *AiManager {
	return &AiManager{session: session}
}

func (m *AiManager) Ask(ctx context.Context, body *schemas.AiAsk) (*schemas.AiResponseFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/ai"+"/ask")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiResponseFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiManager) CreateTextGen(ctx context.Context, body *schemas.AiTextGen) (*schemas.AiResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/ai"+"/text_gen")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// AiGetAgentDefaultOptions carries the optional parameters.
type AiGetAgentDefaultOptions struct {
	Language *string
	Model    *string
}

func (m *AiManager) GetAgentDefault(ctx context.Context, mode schemas.GetAgentDefaultMode, opts *AiGetAgentDefaultOptions) (*schemas.AiAgent, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/ai_agent_default")
	req = gantryruntime.WithQuery(req, "mode", string(mode))
	if opts != nil {
		if opts.Language != nil {
			req = gantryruntime.WithQuery(req, "language", (*opts.Language))
		}
		if opts.Model != nil {
			req = gantryruntime.WithQuery(req, "model", (*opts.Model))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiAgent)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiManager) Extract(ctx context.Context, body *schemas.AiExtract) (*schemas.AiResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/ai"+"/extract")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiManager) CreateExtractStructured(ctx context.Context, body *schemas.AiExtractStructured) (*schemas.AiExtractStructuredResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/ai"+"/extract_structured")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiExtractStructuredResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
