// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// AiStudioManager groups the "ai_studio" operations.
type AiStudioManager struct {
	session *gantryruntime.Client
}

// NewAiStudioManager builds the manager against a runtime session.
func NewAiStudioManager(session *gantryruntime.Client) *AiStudioManager {
	return &AiStudioManager{session: session}
}

// AiStudioListAiAgentsOptions carries the optional parameters.
type AiStudioListAiAgentsOptions struct {
	Mode              []string
	Fields            []string
	AgentState        []string
	IncludeBoxDefault *bool
	Marker            *string
	Limit             *int64
}

func (m *AiStudioManager) listAiAgentsPage(ctx context.Context, opts *AiStudioListAiAgentsOptions) (*schemas.AiMultipleAgentResponse, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/ai_agents")
	if opts != nil {
		if opts.Mode != nil {
			req = gantryruntime.WithQuery(req, "mode", strings.Join(opts.Mode, ","))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.AgentState != nil {
			req = gantryruntime.WithQuery(req, "agent_state", strings.Join(opts.AgentState, ","))
		}
		if opts.IncludeBoxDefault != nil {
			req = gantryruntime.WithQuery(req, "include_box_default", strconv.FormatBool((*opts.IncludeBoxDefault)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiMultipleAgentResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiStudioManager) ListAiAgents(ctx context.Context, opts *AiStudioListAiAgentsOptions) iter.Seq2[*schemas.AiSingleAgentResponseFull, error] {
	return func(yield func(*schemas.AiSingleAgentResponseFull, error) bool) {
		var o AiStudioListAiAgentsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listAiAgentsPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *AiStudioManager) CreateAiAgents(ctx context.Context, body *schemas.CreateAiAgent) (*schemas.AiSingleAgentResponseFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/ai_agents")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiSingleAgentResponseFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// AiStudioGetAiAgentOptions carries the optional parameters.
type AiStudioGetAiAgentOptions struct {
	Fields []string
}

func (m *AiStudioManager) GetAiAgent(ctx context.Context, agentId string, opts *AiStudioGetAiAgentOptions) (*schemas.AiSingleAgentResponseFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/ai_agents"+"/"+url.PathEscape(agentId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiSingleAgentResponseFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiStudioManager) UpdateAiAgent(ctx context.Context, agentId string, body *schemas.CreateAiAgent) (*schemas.AiSingleAgentResponseFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/ai_agents"+"/"+url.PathEscape(agentId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AiSingleAgentResponseFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AiStudioManager) DeleteAiAgent(ctx context.Context, agentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/ai_agents"+"/"+url.PathEscape(agentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
