// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// AppItemAssociationsManager groups the "app_item_associations" operations.
type AppItemAssociationsManager struct {
	session *gantryruntime.Client
}

// NewAppItemAssociationsManager builds the manager against a runtime session.
func NewAppItemAssociationsManager(session *gantryruntime.Client) *AppItemAssociationsManager {
	return &AppItemAssociationsManager{session: session}
}

// AppItemAssociationsListFileOptions carries the optional parameters.
type AppItemAssociationsListFileOptions struct {
	Limit           *int64
	Marker          *string
	ApplicationType *string
}

func (m *AppItemAssociationsManager) listFilePage(ctx context.Context, fileId string, opts *AppItemAssociationsListFileOptions) (*schemas.AppItemAssociations, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/app_item_associations")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.ApplicationType != nil {
			req = gantryruntime.WithQuery(req, "application_type", (*opts.ApplicationType))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AppItemAssociations)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AppItemAssociationsManager) ListFile(ctx context.Context, fileId string, opts *AppItemAssociationsListFileOptions) iter.Seq2[*schemas.AppItemAssociation, error] {
	return func(yield func(*schemas.AppItemAssociation, error) bool) {
		var o AppItemAssociationsListFileOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFilePage(ctx, fileId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// AppItemAssociationsListFolderOptions carries the optional parameters.
type AppItemAssociationsListFolderOptions struct {
	Limit           *int64
	Marker          *string
	ApplicationType *string
}

func (m *AppItemAssociationsManager) listFolderPage(ctx context.Context, folderId string, opts *AppItemAssociationsListFolderOptions) (*schemas.AppItemAssociations, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/app_item_associations")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.ApplicationType != nil {
			req = gantryruntime.WithQuery(req, "application_type", (*opts.ApplicationType))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AppItemAssociations)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AppItemAssociationsManager) ListFolder(ctx context.Context, folderId string, opts *AppItemAssociationsListFolderOptions) iter.Seq2[*schemas.AppItemAssociation, error] {
	return func(yield func(*schemas.AppItemAssociation, error) bool) {
		var o AppItemAssociationsListFolderOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFolderPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
