// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ArchivesManager groups the "archives" operations.
type ArchivesManager struct {
	session *gantryruntime.Client
}

// NewArchivesManager builds the manager against a runtime session.
func NewArchivesManager(session *gantryruntime.Client) *ArchivesManager {
	return &ArchivesManager{session: session}
}

// ArchivesListOptions carries the optional parameters.
type ArchivesListOptions struct {
	Limit  *int64
	Marker *string
}

func (m *ArchivesManager) listPage(ctx context.Context, opts *ArchivesListOptions) (*schemas.Archives, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/archives")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Archives)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ArchivesManager) List(ctx context.Context, opts *ArchivesListOptions) iter.Seq2[*schemas.Archive, error] {
	return func(yield func(*schemas.Archive, error) bool) {
		var o ArchivesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ArchivesManager) Create(ctx context.Context, body *schemas.ArchiveCreateRequest) (*schemas.Archive, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/archives")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Archive)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ArchivesManager) Update(ctx context.Context, archiveId string, body *schemas.ArchiveUpdateRequest) (*schemas.Archive, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/archives"+"/"+url.PathEscape(archiveId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Archive)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ArchivesManager) Delete(ctx context.Context, archiveId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/archives"+"/"+url.PathEscape(archiveId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
