// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// AuthorizationManager groups the "authorization" operations.
type AuthorizationManager struct {
	session *gantryruntime.Client
}

// NewAuthorizationManager builds the manager against a runtime session.
func NewAuthorizationManager(session *gantryruntime.Client) *AuthorizationManager {
	return &AuthorizationManager{session: session}
}

// AuthorizationAuthorizeOptions carries the optional parameters.
type AuthorizationAuthorizeOptions struct {
	RedirectUri *string
	State       *string
	Scope       *string
}

func (m *AuthorizationManager) Authorize(ctx context.Context, responseType schemas.GetAuthorizeResponseType, clientId string, opts *AuthorizationAuthorizeOptions) (string, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("oauth_authorize")+"/authorize")
	req = gantryruntime.WithQuery(req, "response_type", string(responseType))
	req = gantryruntime.WithQuery(req, "client_id", clientId)
	if opts != nil {
		if opts.RedirectUri != nil {
			req = gantryruntime.WithQuery(req, "redirect_uri", (*opts.RedirectUri))
		}
		if opts.State != nil {
			req = gantryruntime.WithQuery(req, "state", (*opts.State))
		}
		if opts.Scope != nil {
			req = gantryruntime.WithQuery(req, "scope", (*opts.Scope))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return "", err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func (m *AuthorizationManager) CreateOauth2Token(ctx context.Context, body *schemas.PostOAuth2Token) (*schemas.AccessToken, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api_root")+"/oauth2"+"/token")
	form := url.Values{}
	form.Set("grant_type", string(body.GrantType))
	if body.ClientId != nil {
		form.Set("client_id", (*body.ClientId))
	}
	if body.ClientSecret != nil {
		form.Set("client_secret", (*body.ClientSecret))
	}
	if body.Code != nil {
		form.Set("code", (*body.Code))
	}
	if body.RefreshToken != nil {
		form.Set("refresh_token", (*body.RefreshToken))
	}
	if body.Assertion != nil {
		form.Set("assertion", (*body.Assertion))
	}
	if body.SubjectToken != nil {
		form.Set("subject_token", (*body.SubjectToken))
	}
	if body.SubjectTokenType != nil {
		form.Set("subject_token_type", string((*body.SubjectTokenType)))
	}
	if body.ActorToken != nil {
		form.Set("actor_token", (*body.ActorToken))
	}
	if body.ActorTokenType != nil {
		form.Set("actor_token_type", string((*body.ActorTokenType)))
	}
	if body.Scope != nil {
		form.Set("scope", (*body.Scope))
	}
	if body.Resource != nil {
		form.Set("resource", (*body.Resource))
	}
	if body.BoxSubjectType != nil {
		form.Set("box_subject_type", string((*body.BoxSubjectType)))
	}
	if body.BoxSubjectId != nil {
		form.Set("box_subject_id", (*body.BoxSubjectId))
	}
	if body.BoxSharedLink != nil {
		form.Set("box_shared_link", (*body.BoxSharedLink))
	}
	req = gantryruntime.WithFormBody(req, []byte(form.Encode()))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AccessToken)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AuthorizationManager) CreateOauth2TokenRefresh(ctx context.Context, body *schemas.PostOAuth2TokenRefreshAccessToken) (*schemas.AccessToken, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api_root")+"/oauth2"+"/token")
	form := url.Values{}
	form.Set("grant_type", string(body.GrantType))
	form.Set("client_id", body.ClientId)
	form.Set("client_secret", body.ClientSecret)
	form.Set("refresh_token", body.RefreshToken)
	req = gantryruntime.WithFormBody(req, []byte(form.Encode()))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AccessToken)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AuthorizationManager) RevokeOauth2(ctx context.Context, body *schemas.PostOAuth2Revoke) error {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api_root")+"/oauth2"+"/revoke")
	form := url.Values{}
	if body.ClientId != nil {
		form.Set("client_id", (*body.ClientId))
	}
	if body.ClientSecret != nil {
		form.Set("client_secret", (*body.ClientSecret))
	}
	if body.Token != nil {
		form.Set("token", (*body.Token))
	}
	req = gantryruntime.WithFormBody(req, []byte(form.Encode()))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
