// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// AutomateWorkflowsManager groups the "automate_workflows" operations.
type AutomateWorkflowsManager struct {
	session *gantryruntime.Client
}

// NewAutomateWorkflowsManager builds the manager against a runtime session.
func NewAutomateWorkflowsManager(session *gantryruntime.Client) *AutomateWorkflowsManager {
	return &AutomateWorkflowsManager{session: session}
}

// AutomateWorkflowsListOptions carries the optional parameters.
type AutomateWorkflowsListOptions struct {
	Limit  *int64
	Marker *string
}

func (m *AutomateWorkflowsManager) listPage(ctx context.Context, folderId string, opts *AutomateWorkflowsListOptions) (*schemas.AutomateWorkflows, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/automate_workflows")
	req = gantryruntime.WithQuery(req, "folder_id", folderId)
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2026.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AutomateWorkflows)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AutomateWorkflowsManager) List(ctx context.Context, folderId string, opts *AutomateWorkflowsListOptions) iter.Seq2[*schemas.AutomateWorkflowAction, error] {
	return func(yield func(*schemas.AutomateWorkflowAction, error) bool) {
		var o AutomateWorkflowsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *AutomateWorkflowsManager) Start(ctx context.Context, workflowId string, body *schemas.AutomateWorkflowStartRequest) error {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/automate_workflows"+"/"+url.PathEscape(workflowId)+"/start")
	req = gantryruntime.WithHeader(req, "box-version", "2026.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
