// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"io"
	"net/url"
)

// AvatarsManager groups the "avatars" operations.
type AvatarsManager struct {
	session *gantryruntime.Client
}

// NewAvatarsManager builds the manager against a runtime session.
func NewAvatarsManager(session *gantryruntime.Client) *AvatarsManager {
	return &AvatarsManager{session: session}
}

func (m *AvatarsManager) GetUserAvatar(ctx context.Context, userId string) (io.Reader, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/avatar")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	return gantryruntime.ResponseStream(resp), nil
}

func (m *AvatarsManager) CreateUserAvatar(ctx context.Context, userId string, body *schemas.UserAvatarCreateRequest) (*schemas.UserAvatar, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/avatar")
	attributes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithMultipartBody(req, attributes, "file", nil)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UserAvatar)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *AvatarsManager) DeleteUserAvatar(ctx context.Context, userId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/avatar")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
