// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"io"
	"iter"
	"net/url"
	"strconv"
)

// ChunkedUploadsManager groups the "chunked_uploads" operations.
type ChunkedUploadsManager struct {
	session *gantryruntime.Client
}

// NewChunkedUploadsManager builds the manager against a runtime session.
func NewChunkedUploadsManager(session *gantryruntime.Client) *ChunkedUploadsManager {
	return &ChunkedUploadsManager{session: session}
}

func (m *ChunkedUploadsManager) CreateFileUploadSessions(ctx context.Context, body *schemas.FileUploadSessionsCreateRequest) (*schemas.UploadSession, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("upload")+"/files"+"/upload_sessions")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadSession)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ChunkedUploadsManager) CreateFileByIdUploadSessions(ctx context.Context, fileId string, body *schemas.FileIdUploadSessionsCreateRequest) (*schemas.UploadSession, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("upload")+"/files"+"/"+url.PathEscape(fileId)+"/upload_sessions")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadSession)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ChunkedUploadsManager) GetFileUploadSession(ctx context.Context, uploadSessionId string) (*schemas.UploadSession, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("upload_session")+"/files"+"/upload_sessions"+"/"+url.PathEscape(uploadSessionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadSession)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ChunkedUploadsManager) UpdateFileUploadSession(ctx context.Context, uploadSessionId string, digest string, contentRange string, body io.Reader) (*schemas.UploadedPart, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("upload_session")+"/files"+"/upload_sessions"+"/"+url.PathEscape(uploadSessionId))
	req = gantryruntime.WithHeader(req, "digest", digest)
	req = gantryruntime.WithHeader(req, "content-range", contentRange)
	req = gantryruntime.WithStreamBody(req, body, "application/octet-stream")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadedPart)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ChunkedUploadsManager) DeleteFileUploadSession(ctx context.Context, uploadSessionId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("upload_session")+"/files"+"/upload_sessions"+"/"+url.PathEscape(uploadSessionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// ChunkedUploadsListFileUploadSessionPartsOptions carries the optional parameters.
type ChunkedUploadsListFileUploadSessionPartsOptions struct {
	Offset *int64
	Limit  *int64
}

func (m *ChunkedUploadsManager) listFileUploadSessionPartsPage(ctx context.Context, uploadSessionId string, opts *ChunkedUploadsListFileUploadSessionPartsOptions) (*schemas.UploadParts, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("upload_session")+"/files"+"/upload_sessions"+"/"+url.PathEscape(uploadSessionId)+"/parts")
	if opts != nil {
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadParts)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ChunkedUploadsManager) ListFileUploadSessionParts(ctx context.Context, uploadSessionId string, opts *ChunkedUploadsListFileUploadSessionPartsOptions) iter.Seq2[*schemas.UploadPart, error] {
	return func(yield func(*schemas.UploadPart, error) bool) {
		var o ChunkedUploadsListFileUploadSessionPartsOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listFileUploadSessionPartsPage(ctx, uploadSessionId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// ChunkedUploadsCommitFileUploadSessionOptions carries the optional parameters.
type ChunkedUploadsCommitFileUploadSessionOptions struct {
	IfMatch     *string
	IfNoneMatch *string
}

func (m *ChunkedUploadsManager) CommitFileUploadSession(ctx context.Context, uploadSessionId string, digest string, body *schemas.FileUploadSessionCommitRequest, opts *ChunkedUploadsCommitFileUploadSessionOptions) (*schemas.Files, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("upload_session")+"/files"+"/upload_sessions"+"/"+url.PathEscape(uploadSessionId)+"/commit")
	req = gantryruntime.WithHeader(req, "digest", digest)
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Files)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
