// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// ClassificationsManager groups the "classifications" operations.
type ClassificationsManager struct {
	session *gantryruntime.Client
}

// NewClassificationsManager builds the manager against a runtime session.
func NewClassificationsManager(session *gantryruntime.Client) *ClassificationsManager {
	return &ClassificationsManager{session: session}
}

func (m *ClassificationsManager) Get(ctx context.Context) (*schemas.ClassificationTemplate, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/enterprise"+"/securityClassification-6VMVochwUWo"+"/schema")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ClassificationTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ClassificationsManager) UpdateAdd(ctx context.Context, body []schemas.ClassificationUpdateRequest) (*schemas.ClassificationTemplate, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/metadata_templates"+"/enterprise"+"/securityClassification-6VMVochwUWo"+"/schema")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ClassificationTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ClassificationsManager) UpdateUpdate(ctx context.Context, body []schemas.ClassificationUpdateRequest2) (*schemas.ClassificationTemplate, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/metadata_templates"+"/enterprise"+"/securityClassification-6VMVochwUWo"+"/schema")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ClassificationTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ClassificationsManager) CreateMetadataTemplateSchemaClassifications(ctx context.Context, body *schemas.MetadataTemplateSchemaCreateRequest) (*schemas.ClassificationTemplate, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_templates"+"/schema")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ClassificationTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
