// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// CollaborationAllowlistEntriesManager groups the "collaboration_allowlist_entries" operations.
type CollaborationAllowlistEntriesManager struct {
	session *gantryruntime.Client
}

// NewCollaborationAllowlistEntriesManager builds the manager against a runtime session.
func NewCollaborationAllowlistEntriesManager(session *gantryruntime.Client) *CollaborationAllowlistEntriesManager {
	return &CollaborationAllowlistEntriesManager{session: session}
}

// CollaborationAllowlistEntriesListCollaborationWhitelistEntriesOptions carries the optional parameters.
type CollaborationAllowlistEntriesListCollaborationWhitelistEntriesOptions struct {
	Marker *string
	Limit  *int64
}

func (m *CollaborationAllowlistEntriesManager) listCollaborationWhitelistEntriesPage(ctx context.Context, opts *CollaborationAllowlistEntriesListCollaborationWhitelistEntriesOptions) (*schemas.CollaborationAllowlistEntries, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaboration_whitelist_entries")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistEntries)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistEntriesManager) ListCollaborationWhitelistEntries(ctx context.Context, opts *CollaborationAllowlistEntriesListCollaborationWhitelistEntriesOptions) iter.Seq2[*schemas.CollaborationAllowlistEntry, error] {
	return func(yield func(*schemas.CollaborationAllowlistEntry, error) bool) {
		var o CollaborationAllowlistEntriesListCollaborationWhitelistEntriesOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listCollaborationWhitelistEntriesPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *CollaborationAllowlistEntriesManager) CreateCollaborationWhitelistEntries(ctx context.Context, body *schemas.CollaborationWhitelistEntriesCreateRequest) (*schemas.CollaborationAllowlistEntry, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/collaboration_whitelist_entries")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistEntry)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistEntriesManager) GetCollaborationWhitelistEntry(ctx context.Context, collaborationWhitelistEntryId string) (*schemas.CollaborationAllowlistEntry, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaboration_whitelist_entries"+"/"+url.PathEscape(collaborationWhitelistEntryId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistEntry)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistEntriesManager) DeleteCollaborationWhitelistEntry(ctx context.Context, collaborationWhitelistEntryId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/collaboration_whitelist_entries"+"/"+url.PathEscape(collaborationWhitelistEntryId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
