// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// CollaborationAllowlistExemptTargetsManager groups the "collaboration_allowlist_exempt_targets" operations.
type CollaborationAllowlistExemptTargetsManager struct {
	session *gantryruntime.Client
}

// NewCollaborationAllowlistExemptTargetsManager builds the manager against a runtime session.
func NewCollaborationAllowlistExemptTargetsManager(session *gantryruntime.Client) *CollaborationAllowlistExemptTargetsManager {
	return &CollaborationAllowlistExemptTargetsManager{session: session}
}

// CollaborationAllowlistExemptTargetsListCollaborationWhitelistExemptTargetsOptions carries the optional parameters.
type CollaborationAllowlistExemptTargetsListCollaborationWhitelistExemptTargetsOptions struct {
	Marker *string
	Limit  *int64
}

func (m *CollaborationAllowlistExemptTargetsManager) listCollaborationWhitelistExemptTargetsPage(ctx context.Context, opts *CollaborationAllowlistExemptTargetsListCollaborationWhitelistExemptTargetsOptions) (*schemas.CollaborationAllowlistExemptTargets, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaboration_whitelist_exempt_targets")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistExemptTargets)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistExemptTargetsManager) ListCollaborationWhitelistExemptTargets(ctx context.Context, opts *CollaborationAllowlistExemptTargetsListCollaborationWhitelistExemptTargetsOptions) iter.Seq2[*schemas.CollaborationAllowlistExemptTarget, error] {
	return func(yield func(*schemas.CollaborationAllowlistExemptTarget, error) bool) {
		var o CollaborationAllowlistExemptTargetsListCollaborationWhitelistExemptTargetsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listCollaborationWhitelistExemptTargetsPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *CollaborationAllowlistExemptTargetsManager) CreateCollaborationWhitelistExemptTargets(ctx context.Context, body *schemas.CollaborationWhitelistExemptTargetsCreateRequest) (*schemas.CollaborationAllowlistExemptTarget, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/collaboration_whitelist_exempt_targets")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistExemptTarget)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistExemptTargetsManager) GetCollaborationWhitelistExemptTarget(ctx context.Context, collaborationWhitelistExemptTargetId string) (*schemas.CollaborationAllowlistExemptTarget, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaboration_whitelist_exempt_targets"+"/"+url.PathEscape(collaborationWhitelistExemptTargetId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationAllowlistExemptTarget)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollaborationAllowlistExemptTargetsManager) DeleteCollaborationWhitelistExemptTarget(ctx context.Context, collaborationWhitelistExemptTargetId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/collaboration_whitelist_exempt_targets"+"/"+url.PathEscape(collaborationWhitelistExemptTargetId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
