// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// CollectionsManager groups the "collections" operations.
type CollectionsManager struct {
	session *gantryruntime.Client
}

// NewCollectionsManager builds the manager against a runtime session.
func NewCollectionsManager(session *gantryruntime.Client) *CollectionsManager {
	return &CollectionsManager{session: session}
}

// CollectionsListOptions carries the optional parameters.
type CollectionsListOptions struct {
	Fields []string
	Offset *int64
	Limit  *int64
}

func (m *CollectionsManager) listPage(ctx context.Context, opts *CollectionsListOptions) (*schemas.Collections, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collections")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collections)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollectionsManager) List(ctx context.Context, opts *CollectionsListOptions) iter.Seq2[*schemas.Collection, error] {
	return func(yield func(*schemas.Collection, error) bool) {
		var o CollectionsListOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// CollectionsListItemsOptions carries the optional parameters.
type CollectionsListItemsOptions struct {
	Fields []string
	Offset *int64
	Limit  *int64
}

func (m *CollectionsManager) listItemsPage(ctx context.Context, collectionId string, opts *CollectionsListItemsOptions) (*schemas.ItemsOffsetPaginated, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collections"+"/"+url.PathEscape(collectionId)+"/items")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ItemsOffsetPaginated)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CollectionsManager) ListItems(ctx context.Context, collectionId string, opts *CollectionsListItemsOptions) iter.Seq2[*schemas.Item, error] {
	return func(yield func(*schemas.Item, error) bool) {
		var o CollectionsListItemsOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listItemsPage(ctx, collectionId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

func (m *CollectionsManager) Get(ctx context.Context, collectionId string) (*schemas.Collection, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collections"+"/"+url.PathEscape(collectionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collection)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
