// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// CommentsManager groups the "comments" operations.
type CommentsManager struct {
	session *gantryruntime.Client
}

// NewCommentsManager builds the manager against a runtime session.
func NewCommentsManager(session *gantryruntime.Client) *CommentsManager {
	return &CommentsManager{session: session}
}

// CommentsListFileOptions carries the optional parameters.
type CommentsListFileOptions struct {
	Fields []string
	Limit  *int64
	Offset *int64
}

func (m *CommentsManager) listFilePage(ctx context.Context, fileId string, opts *CommentsListFileOptions) (*schemas.Comments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/comments")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Comments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CommentsManager) ListFile(ctx context.Context, fileId string, opts *CommentsListFileOptions) iter.Seq2[*schemas.CommentFull, error] {
	return func(yield func(*schemas.CommentFull, error) bool) {
		var o CommentsListFileOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listFilePage(ctx, fileId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// CommentsGetOptions carries the optional parameters.
type CommentsGetOptions struct {
	Fields []string
}

func (m *CommentsManager) Get(ctx context.Context, commentId string, opts *CommentsGetOptions) (*schemas.CommentFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/comments"+"/"+url.PathEscape(commentId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CommentFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// CommentsUpdateOptions carries the optional parameters.
type CommentsUpdateOptions struct {
	Fields []string
}

func (m *CommentsManager) Update(ctx context.Context, commentId string, body *schemas.CommentUpdateRequest, opts *CommentsUpdateOptions) (*schemas.CommentFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/comments"+"/"+url.PathEscape(commentId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CommentFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *CommentsManager) Delete(ctx context.Context, commentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/comments"+"/"+url.PathEscape(commentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// CommentsCreateOptions carries the optional parameters.
type CommentsCreateOptions struct {
	Fields []string
}

func (m *CommentsManager) Create(ctx context.Context, body *schemas.CommentCreateRequest, opts *CommentsCreateOptions) (*schemas.CommentFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/comments")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CommentFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
