// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// DevicePinnersManager groups the "device_pinners" operations.
type DevicePinnersManager struct {
	session *gantryruntime.Client
}

// NewDevicePinnersManager builds the manager against a runtime session.
func NewDevicePinnersManager(session *gantryruntime.Client) *DevicePinnersManager {
	return &DevicePinnersManager{session: session}
}

func (m *DevicePinnersManager) Get(ctx context.Context, devicePinnerId string) (*schemas.DevicePinner, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/device_pinners"+"/"+url.PathEscape(devicePinnerId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DevicePinner)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DevicePinnersManager) Delete(ctx context.Context, devicePinnerId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/device_pinners"+"/"+url.PathEscape(devicePinnerId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// DevicePinnersListEnterpriseOptions carries the optional parameters.
type DevicePinnersListEnterpriseOptions struct {
	Marker    *string
	Limit     *int64
	Direction *schemas.OrderDirection
}

func (m *DevicePinnersManager) listEnterprisePage(ctx context.Context, enterpriseId string, opts *DevicePinnersListEnterpriseOptions) (*schemas.DevicePinners, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/enterprises"+"/"+url.PathEscape(enterpriseId)+"/device_pinners")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DevicePinners)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DevicePinnersManager) ListEnterprise(ctx context.Context, enterpriseId string, opts *DevicePinnersListEnterpriseOptions) iter.Seq2[*schemas.DevicePinner, error] {
	return func(yield func(*schemas.DevicePinner, error) bool) {
		var o DevicePinnersListEnterpriseOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listEnterprisePage(ctx, enterpriseId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil {
				return
			}
			cursor := *page.NextMarker
			next := strconv.FormatInt(cursor, 10)
			o.Marker = &next
		}
	}
}
