// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// DocgenManager groups the "docgen" operations.
type DocgenManager struct {
	session *gantryruntime.Client
}

// NewDocgenManager builds the manager against a runtime session.
func NewDocgenManager(session *gantryruntime.Client) *DocgenManager {
	return &DocgenManager{session: session}
}

func (m *DocgenManager) GetJob(ctx context.Context, jobId string) (*schemas.DocGenJob, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_jobs"+"/"+url.PathEscape(jobId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenJob)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// DocgenListJobsOptions carries the optional parameters.
type DocgenListJobsOptions struct {
	Marker *string
	Limit  *int64
}

func (m *DocgenManager) listJobsPage(ctx context.Context, opts *DocgenListJobsOptions) (*schemas.DocGenJobsFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_jobs")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenJobsFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenManager) ListJobs(ctx context.Context, opts *DocgenListJobsOptions) iter.Seq2[*schemas.DocGenJobFull, error] {
	return func(yield func(*schemas.DocGenJobFull, error) bool) {
		var o DocgenListJobsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listJobsPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// DocgenListBatchJobOptions carries the optional parameters.
type DocgenListBatchJobOptions struct {
	Marker *string
	Limit  *int64
}

func (m *DocgenManager) listBatchJobPage(ctx context.Context, batchId string, opts *DocgenListBatchJobOptions) (*schemas.DocGenJobs, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_batch_jobs"+"/"+url.PathEscape(batchId))
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenJobs)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenManager) ListBatchJob(ctx context.Context, batchId string, opts *DocgenListBatchJobOptions) iter.Seq2[*schemas.DocGenJob, error] {
	return func(yield func(*schemas.DocGenJob, error) bool) {
		var o DocgenListBatchJobOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listBatchJobPage(ctx, batchId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *DocgenManager) CreateBatches(ctx context.Context, body *schemas.DocGenBatchCreateRequest) (*schemas.DocGenBatchBase, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/docgen_batches")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenBatchBase)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
