// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// DocgenTemplateManager groups the "docgen_template" operations.
type DocgenTemplateManager struct {
	session *gantryruntime.Client
}

// NewDocgenTemplateManager builds the manager against a runtime session.
func NewDocgenTemplateManager(session *gantryruntime.Client) *DocgenTemplateManager {
	return &DocgenTemplateManager{session: session}
}

// DocgenTemplateListDocgenTemplatesOptions carries the optional parameters.
type DocgenTemplateListDocgenTemplatesOptions struct {
	Marker *string
	Limit  *int64
}

func (m *DocgenTemplateManager) listDocgenTemplatesPage(ctx context.Context, opts *DocgenTemplateListDocgenTemplatesOptions) (*schemas.DocGenTemplates, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_templates")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenTemplates)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenTemplateManager) ListDocgenTemplates(ctx context.Context, opts *DocgenTemplateListDocgenTemplatesOptions) iter.Seq2[*schemas.DocGenTemplate, error] {
	return func(yield func(*schemas.DocGenTemplate, error) bool) {
		var o DocgenTemplateListDocgenTemplatesOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listDocgenTemplatesPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *DocgenTemplateManager) CreateDocgenTemplates(ctx context.Context, body *schemas.DocGenTemplateCreateRequest) (*schemas.DocGenTemplateBase, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/docgen_templates")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenTemplateBase)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenTemplateManager) GetDocgenTemplate(ctx context.Context, templateId string) (*schemas.DocGenTemplate, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_templates"+"/"+url.PathEscape(templateId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenTemplateManager) DeleteDocgenTemplate(ctx context.Context, templateId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/docgen_templates"+"/"+url.PathEscape(templateId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// DocgenTemplateListDocgenTemplateTagsOptions carries the optional parameters.
type DocgenTemplateListDocgenTemplateTagsOptions struct {
	TemplateVersionId *string
	Marker            *string
	Limit             *int64
}

func (m *DocgenTemplateManager) listDocgenTemplateTagsPage(ctx context.Context, templateId string, opts *DocgenTemplateListDocgenTemplateTagsOptions) (*schemas.DocGenTags, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_templates"+"/"+url.PathEscape(templateId)+"/tags")
	if opts != nil {
		if opts.TemplateVersionId != nil {
			req = gantryruntime.WithQuery(req, "template_version_id", (*opts.TemplateVersionId))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenTags)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenTemplateManager) ListDocgenTemplateTags(ctx context.Context, templateId string, opts *DocgenTemplateListDocgenTemplateTagsOptions) iter.Seq2[*schemas.DocGenTag, error] {
	return func(yield func(*schemas.DocGenTag, error) bool) {
		var o DocgenTemplateListDocgenTemplateTagsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listDocgenTemplateTagsPage(ctx, templateId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// DocgenTemplateListJobOptions carries the optional parameters.
type DocgenTemplateListJobOptions struct {
	Marker *string
	Limit  *int64
}

func (m *DocgenTemplateManager) listJobPage(ctx context.Context, templateId string, opts *DocgenTemplateListJobOptions) (*schemas.DocGenJobs, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/docgen_template_jobs"+"/"+url.PathEscape(templateId))
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.DocGenJobs)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *DocgenTemplateManager) ListJob(ctx context.Context, templateId string, opts *DocgenTemplateListJobOptions) iter.Seq2[*schemas.DocGenJob, error] {
	return func(yield func(*schemas.DocGenJob, error) bool) {
		var o DocgenTemplateListJobOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listJobPage(ctx, templateId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
