// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"io"
	"net/url"
)

// DownloadsManager groups the "downloads" operations.
type DownloadsManager struct {
	session *gantryruntime.Client
}

// NewDownloadsManager builds the manager against a runtime session.
func NewDownloadsManager(session *gantryruntime.Client) *DownloadsManager {
	return &DownloadsManager{session: session}
}

// DownloadsGetFileContentOptions carries the optional parameters.
type DownloadsGetFileContentOptions struct {
	Range       *string
	Boxapi      *string
	Version     *string
	AccessToken *string
}

func (m *DownloadsManager) GetFileContent(ctx context.Context, fileId string, opts *DownloadsGetFileContentOptions) (io.Reader, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/content")
	if opts != nil {
		if opts.Range != nil {
			req = gantryruntime.WithHeader(req, "range", (*opts.Range))
		}
		if opts.Boxapi != nil {
			req = gantryruntime.WithHeader(req, "boxapi", (*opts.Boxapi))
		}
		if opts.Version != nil {
			req = gantryruntime.WithQuery(req, "version", (*opts.Version))
		}
		if opts.AccessToken != nil {
			req = gantryruntime.WithQuery(req, "access_token", (*opts.AccessToken))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	return gantryruntime.ResponseStream(resp), nil
}
