// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// EmailAliasesManager groups the "email_aliases" operations.
type EmailAliasesManager struct {
	session *gantryruntime.Client
}

// NewEmailAliasesManager builds the manager against a runtime session.
func NewEmailAliasesManager(session *gantryruntime.Client) *EmailAliasesManager {
	return &EmailAliasesManager{session: session}
}

func (m *EmailAliasesManager) ListUser(ctx context.Context, userId string) (*schemas.EmailAliases, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/email_aliases")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.EmailAliases)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *EmailAliasesManager) CreateUser(ctx context.Context, userId string, body *schemas.UserIdCreateRequest) (*schemas.EmailAlias, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/email_aliases")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.EmailAlias)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *EmailAliasesManager) DeleteUser(ctx context.Context, userId string, emailAliasId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/email_aliases"+"/"+url.PathEscape(emailAliasId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
