// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// EnterpriseConfigurationsManager groups the "enterprise_configurations" operations.
type EnterpriseConfigurationsManager struct {
	session *gantryruntime.Client
}

// NewEnterpriseConfigurationsManager builds the manager against a runtime session.
func NewEnterpriseConfigurationsManager(session *gantryruntime.Client) *EnterpriseConfigurationsManager {
	return &EnterpriseConfigurationsManager{session: session}
}

func (m *EnterpriseConfigurationsManager) Get(ctx context.Context, enterpriseId string, categories []string) (*schemas.EnterpriseConfiguration, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/enterprise_configurations"+"/"+url.PathEscape(enterpriseId))
	req = gantryruntime.WithQuery(req, "categories", strings.Join(categories, ","))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.EnterpriseConfiguration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
