// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"strconv"
	"time"
)

// EventsManager groups the "events" operations.
type EventsManager struct {
	session *gantryruntime.Client
}

// NewEventsManager builds the manager against a runtime session.
func NewEventsManager(session *gantryruntime.Client) *EventsManager {
	return &EventsManager{session: session}
}

// EventsListOptions carries the optional parameters.
type EventsListOptions struct {
	StreamType     *schemas.GetStreamType
	StreamPosition *string
	Limit          *int64
	EventType      []schemas.GetEventType
	CreatedAfter   *time.Time
	CreatedBefore  *time.Time
}

func (m *EventsManager) List(ctx context.Context, opts *EventsListOptions) (*schemas.Events, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/events")
	if opts != nil {
		if opts.StreamType != nil {
			req = gantryruntime.WithQuery(req, "stream_type", string((*opts.StreamType)))
		}
		if opts.StreamPosition != nil {
			req = gantryruntime.WithQuery(req, "stream_position", (*opts.StreamPosition))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.EventType != nil {
			req = gantryruntime.WithQuery(req, "event_type", joinStringLike(opts.EventType))
		}
		if opts.CreatedAfter != nil {
			req = gantryruntime.WithQuery(req, "created_after", (*opts.CreatedAfter).Format(time.RFC3339))
		}
		if opts.CreatedBefore != nil {
			req = gantryruntime.WithQuery(req, "created_before", (*opts.CreatedBefore).Format(time.RFC3339))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Events)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *EventsManager) Options(ctx context.Context) (*schemas.RealtimeServers, error) {
	req := m.session.NewRequest("OPTIONS", m.session.BaseUrl("api")+"/events")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RealtimeServers)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
