// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// ExternalUsersManager groups the "external_users" operations.
type ExternalUsersManager struct {
	session *gantryruntime.Client
}

// NewExternalUsersManager builds the manager against a runtime session.
func NewExternalUsersManager(session *gantryruntime.Client) *ExternalUsersManager {
	return &ExternalUsersManager{session: session}
}

func (m *ExternalUsersManager) CreateSubmitDeleteJob(ctx context.Context, body *schemas.ExternalUsersSubmitDeleteJobRequest) (*schemas.ExternalUsersSubmitDeleteJobResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/external_users"+"/submit_delete_job")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ExternalUsersSubmitDeleteJobResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
