// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FileRequestsManager groups the "file_requests" operations.
type FileRequestsManager struct {
	session *gantryruntime.Client
}

// NewFileRequestsManager builds the manager against a runtime session.
func NewFileRequestsManager(session *gantryruntime.Client) *FileRequestsManager {
	return &FileRequestsManager{session: session}
}

func (m *FileRequestsManager) Get(ctx context.Context, fileRequestId string) (*schemas.FileRequest, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/file_requests"+"/"+url.PathEscape(fileRequestId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FileRequestsUpdateOptions carries the optional parameters.
type FileRequestsUpdateOptions struct {
	IfMatch *string
}

func (m *FileRequestsManager) Update(ctx context.Context, fileRequestId string, body *schemas.FileRequestUpdateRequest, opts *FileRequestsUpdateOptions) (*schemas.FileRequest, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/file_requests"+"/"+url.PathEscape(fileRequestId))
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileRequestsManager) Delete(ctx context.Context, fileRequestId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/file_requests"+"/"+url.PathEscape(fileRequestId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *FileRequestsManager) Copy(ctx context.Context, fileRequestId string, body *schemas.FileRequestCopyRequest) (*schemas.FileRequest, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/file_requests"+"/"+url.PathEscape(fileRequestId)+"/copy")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
