// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FileClassificationsManager groups the "file_classifications" operations.
type FileClassificationsManager struct {
	session *gantryruntime.Client
}

// NewFileClassificationsManager builds the manager against a runtime session.
func NewFileClassificationsManager(session *gantryruntime.Client) *FileClassificationsManager {
	return &FileClassificationsManager{session: session}
}

func (m *FileClassificationsManager) Get(ctx context.Context, fileId string) (*schemas.Classification, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileClassificationsManager) Update(ctx context.Context, fileId string, body []schemas.FileClassificationUpdateRequest) (*schemas.Classification, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileClassificationsManager) Create(ctx context.Context, fileId string, body *schemas.FileClassificationCreateRequest) (*schemas.Classification, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileClassificationsManager) Delete(ctx context.Context, fileId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
