// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// FileVersionsManager groups the "file_versions" operations.
type FileVersionsManager struct {
	session *gantryruntime.Client
}

// NewFileVersionsManager builds the manager against a runtime session.
func NewFileVersionsManager(session *gantryruntime.Client) *FileVersionsManager {
	return &FileVersionsManager{session: session}
}

// FileVersionsListFileVersionsOptions carries the optional parameters.
type FileVersionsListFileVersionsOptions struct {
	Fields []string
	Limit  *int64
	Offset *int64
}

func (m *FileVersionsManager) listFileVersionsPage(ctx context.Context, fileId string, opts *FileVersionsListFileVersionsOptions) (*schemas.FileVersions, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/versions")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersions)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileVersionsManager) ListFileVersions(ctx context.Context, fileId string, opts *FileVersionsListFileVersionsOptions) iter.Seq2[*schemas.FileVersionFull, error] {
	return func(yield func(*schemas.FileVersionFull, error) bool) {
		var o FileVersionsListFileVersionsOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listFileVersionsPage(ctx, fileId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// FileVersionsGetFileVersionOptions carries the optional parameters.
type FileVersionsGetFileVersionOptions struct {
	Fields []string
}

func (m *FileVersionsManager) GetFileVersion(ctx context.Context, fileId string, fileVersionId string, opts *FileVersionsGetFileVersionOptions) (*schemas.FileVersionFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/versions"+"/"+url.PathEscape(fileVersionId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileVersionsManager) UpdateFileVersion(ctx context.Context, fileId string, fileVersionId string, body *schemas.FileVersionUpdateRequest) (*schemas.FileVersionFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/versions"+"/"+url.PathEscape(fileVersionId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FileVersionsDeleteFileVersionOptions carries the optional parameters.
type FileVersionsDeleteFileVersionOptions struct {
	IfMatch *string
}

func (m *FileVersionsManager) DeleteFileVersion(ctx context.Context, fileId string, fileVersionId string, opts *FileVersionsDeleteFileVersionOptions) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/versions"+"/"+url.PathEscape(fileVersionId))
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// FileVersionsCreateFileVersionCurrentOptions carries the optional parameters.
type FileVersionsCreateFileVersionCurrentOptions struct {
	Fields []string
}

func (m *FileVersionsManager) CreateFileVersionCurrent(ctx context.Context, fileId string, body *schemas.FileVersionCurrentCreateRequest, opts *FileVersionsCreateFileVersionCurrentOptions) (*schemas.FileVersionFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/versions"+"/current")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
