// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"io"
	"net/url"
	"strconv"
	"strings"
)

// FilesManager groups the "files" operations.
type FilesManager struct {
	session *gantryruntime.Client
}

// NewFilesManager builds the manager against a runtime session.
func NewFilesManager(session *gantryruntime.Client) *FilesManager {
	return &FilesManager{session: session}
}

// FilesGetOptions carries the optional parameters.
type FilesGetOptions struct {
	Fields      []string
	IfNoneMatch *string
	Boxapi      *string
	XRepHints   *string
}

func (m *FilesManager) Get(ctx context.Context, fileId string, opts *FilesGetOptions) (*schemas.FileFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
		if opts.Boxapi != nil {
			req = gantryruntime.WithHeader(req, "boxapi", (*opts.Boxapi))
		}
		if opts.XRepHints != nil {
			req = gantryruntime.WithHeader(req, "x-rep-hints", (*opts.XRepHints))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FilesUpdateOptions carries the optional parameters.
type FilesUpdateOptions struct {
	Fields  []string
	IfMatch *string
}

func (m *FilesManager) Update(ctx context.Context, fileId string, body *schemas.FileUpdateRequest, opts *FilesUpdateOptions) (*schemas.FileFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FilesDeleteOptions carries the optional parameters.
type FilesDeleteOptions struct {
	IfMatch *string
}

func (m *FilesManager) Delete(ctx context.Context, fileId string, opts *FilesDeleteOptions) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// FilesCopyOptions carries the optional parameters.
type FilesCopyOptions struct {
	Fields []string
}

func (m *FilesManager) Copy(ctx context.Context, fileId string, body *schemas.FileCopyRequest, opts *FilesCopyOptions) (*schemas.FileFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/copy")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FilesGetThumbnailOptions carries the optional parameters.
type FilesGetThumbnailOptions struct {
	MinHeight *int64
	MinWidth  *int64
	MaxHeight *int64
	MaxWidth  *int64
}

func (m *FilesManager) GetThumbnail(ctx context.Context, fileId string, extension schemas.GetIdThumbnailIdExtension, opts *FilesGetThumbnailOptions) (io.Reader, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/"+"thumbnail."+url.PathEscape(string(extension)))
	if opts != nil {
		if opts.MinHeight != nil {
			req = gantryruntime.WithQuery(req, "min_height", strconv.FormatInt((*opts.MinHeight), 10))
		}
		if opts.MinWidth != nil {
			req = gantryruntime.WithQuery(req, "min_width", strconv.FormatInt((*opts.MinWidth), 10))
		}
		if opts.MaxHeight != nil {
			req = gantryruntime.WithQuery(req, "max_height", strconv.FormatInt((*opts.MaxHeight), 10))
		}
		if opts.MaxWidth != nil {
			req = gantryruntime.WithQuery(req, "max_width", strconv.FormatInt((*opts.MaxWidth), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	return gantryruntime.ResponseStream(resp), nil
}
