// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// FileVersionRetentionsManager groups the "file_version_retentions" operations.
type FileVersionRetentionsManager struct {
	session *gantryruntime.Client
}

// NewFileVersionRetentionsManager builds the manager against a runtime session.
func NewFileVersionRetentionsManager(session *gantryruntime.Client) *FileVersionRetentionsManager {
	return &FileVersionRetentionsManager{session: session}
}

// FileVersionRetentionsListOptions carries the optional parameters.
type FileVersionRetentionsListOptions struct {
	FileId            *string
	FileVersionId     *string
	PolicyId          *string
	DispositionAction *schemas.RetentionPolicyDispositionAction
	DispositionBefore *string
	DispositionAfter  *string
	Limit             *int64
	Marker            *string
}

func (m *FileVersionRetentionsManager) listPage(ctx context.Context, opts *FileVersionRetentionsListOptions) (*schemas.FileVersionRetentions, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/file_version_retentions")
	if opts != nil {
		if opts.FileId != nil {
			req = gantryruntime.WithQuery(req, "file_id", (*opts.FileId))
		}
		if opts.FileVersionId != nil {
			req = gantryruntime.WithQuery(req, "file_version_id", (*opts.FileVersionId))
		}
		if opts.PolicyId != nil {
			req = gantryruntime.WithQuery(req, "policy_id", (*opts.PolicyId))
		}
		if opts.DispositionAction != nil {
			req = gantryruntime.WithQuery(req, "disposition_action", string((*opts.DispositionAction)))
		}
		if opts.DispositionBefore != nil {
			req = gantryruntime.WithQuery(req, "disposition_before", (*opts.DispositionBefore))
		}
		if opts.DispositionAfter != nil {
			req = gantryruntime.WithQuery(req, "disposition_after", (*opts.DispositionAfter))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionRetentions)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileVersionRetentionsManager) List(ctx context.Context, opts *FileVersionRetentionsListOptions) iter.Seq2[*schemas.FileVersionRetention, error] {
	return func(yield func(*schemas.FileVersionRetention, error) bool) {
		var o FileVersionRetentionsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *FileVersionRetentionsManager) Get(ctx context.Context, fileVersionRetentionId string) (*schemas.FileVersionRetention, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/file_version_retentions"+"/"+url.PathEscape(fileVersionRetentionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionRetention)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
