// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// FileVersionLegalHoldsManager groups the "file_version_legal_holds" operations.
type FileVersionLegalHoldsManager struct {
	session *gantryruntime.Client
}

// NewFileVersionLegalHoldsManager builds the manager against a runtime session.
func NewFileVersionLegalHoldsManager(session *gantryruntime.Client) *FileVersionLegalHoldsManager {
	return &FileVersionLegalHoldsManager{session: session}
}

func (m *FileVersionLegalHoldsManager) Get(ctx context.Context, fileVersionLegalHoldId string) (*schemas.FileVersionLegalHold, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/file_version_legal_holds"+"/"+url.PathEscape(fileVersionLegalHoldId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionLegalHold)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FileVersionLegalHoldsListOptions carries the optional parameters.
type FileVersionLegalHoldsListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *FileVersionLegalHoldsManager) listPage(ctx context.Context, policyId string, opts *FileVersionLegalHoldsListOptions) (*schemas.FileVersionLegalHolds, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/file_version_legal_holds")
	req = gantryruntime.WithQuery(req, "policy_id", policyId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionLegalHolds)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileVersionLegalHoldsManager) List(ctx context.Context, policyId string, opts *FileVersionLegalHoldsListOptions) iter.Seq2[*schemas.FileVersionLegalHold, error] {
	return func(yield func(*schemas.FileVersionLegalHold, error) bool) {
		var o FileVersionLegalHoldsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, policyId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
