// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FileMetadataManager groups the "file_metadata" operations.
type FileMetadataManager struct {
	session *gantryruntime.Client
}

// NewFileMetadataManager builds the manager against a runtime session.
func NewFileMetadataManager(session *gantryruntime.Client) *FileMetadataManager {
	return &FileMetadataManager{session: session}
}

// FileMetadataListFileMetadataOptions carries the optional parameters.
type FileMetadataListFileMetadataOptions struct {
	View *string
}

func (m *FileMetadataManager) ListFileMetadata(ctx context.Context, fileId string, opts *FileMetadataListFileMetadataOptions) (*schemas.Metadatas, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata")
	if opts != nil {
		if opts.View != nil {
			req = gantryruntime.WithQuery(req, "view", (*opts.View))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Metadatas)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FileMetadataGetFileMetadataOptions carries the optional parameters.
type FileMetadataGetFileMetadataOptions struct {
	View *string
}

func (m *FileMetadataManager) GetFileMetadata(ctx context.Context, fileId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, opts *FileMetadataGetFileMetadataOptions) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	if opts != nil {
		if opts.View != nil {
			req = gantryruntime.WithQuery(req, "view", (*opts.View))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileMetadataManager) UpdateFileMetadata(ctx context.Context, fileId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, body []schemas.FileMetadataUpdateRequest) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileMetadataManager) CreateFileMetadata(ctx context.Context, fileId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, body map[string]any) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FileMetadataManager) DeleteFileMetadata(ctx context.Context, fileId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
