// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// FoldersManager groups the "folders" operations.
type FoldersManager struct {
	session *gantryruntime.Client
}

// NewFoldersManager builds the manager against a runtime session.
func NewFoldersManager(session *gantryruntime.Client) *FoldersManager {
	return &FoldersManager{session: session}
}

// FoldersGetOptions carries the optional parameters.
type FoldersGetOptions struct {
	Fields      []string
	IfNoneMatch *string
	Boxapi      *string
	Sort        *schemas.GetIdSort
	Direction   *schemas.OrderDirection
	Offset      *int64
	Limit       *int64
}

func (m *FoldersManager) Get(ctx context.Context, folderId string, opts *FoldersGetOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
		if opts.Boxapi != nil {
			req = gantryruntime.WithHeader(req, "boxapi", (*opts.Boxapi))
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", string((*opts.Sort)))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FoldersUpdateOptions carries the optional parameters.
type FoldersUpdateOptions struct {
	Fields  []string
	IfMatch *string
}

func (m *FoldersManager) Update(ctx context.Context, folderId string, body *schemas.FolderUpdateRequest, opts *FoldersUpdateOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FoldersDeleteOptions carries the optional parameters.
type FoldersDeleteOptions struct {
	IfMatch   *string
	Recursive *bool
}

func (m *FoldersManager) Delete(ctx context.Context, folderId string, opts *FoldersDeleteOptions) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
		if opts.Recursive != nil {
			req = gantryruntime.WithQuery(req, "recursive", strconv.FormatBool((*opts.Recursive)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// FoldersListItemsOptions carries the optional parameters.
type FoldersListItemsOptions struct {
	Fields    []string
	Usemarker *bool
	Marker    *string
	Offset    *int64
	Limit     *int64
	Boxapi    *string
	Sort      *schemas.GetIdSort
	Direction *schemas.OrderDirection
}

func (m *FoldersManager) listItemsPage(ctx context.Context, folderId string, opts *FoldersListItemsOptions) (*schemas.Items, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/items")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Usemarker != nil {
			req = gantryruntime.WithQuery(req, "usemarker", strconv.FormatBool((*opts.Usemarker)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Boxapi != nil {
			req = gantryruntime.WithHeader(req, "boxapi", (*opts.Boxapi))
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", string((*opts.Sort)))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Items)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FoldersManager) ListItems(ctx context.Context, folderId string, opts *FoldersListItemsOptions) iter.Seq2[*schemas.Item, error] {
	return func(yield func(*schemas.Item, error) bool) {
		var o FoldersListItemsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listItemsPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// FoldersCreateOptions carries the optional parameters.
type FoldersCreateOptions struct {
	Fields []string
}

func (m *FoldersManager) Create(ctx context.Context, body *schemas.FolderCreateRequest, opts *FoldersCreateOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folders")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// FoldersCopyOptions carries the optional parameters.
type FoldersCopyOptions struct {
	Fields []string
}

func (m *FoldersManager) Copy(ctx context.Context, folderId string, body *schemas.FolderCopyRequest, opts *FoldersCopyOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/copy")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
