// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FolderMetadataManager groups the "folder_metadata" operations.
type FolderMetadataManager struct {
	session *gantryruntime.Client
}

// NewFolderMetadataManager builds the manager against a runtime session.
func NewFolderMetadataManager(session *gantryruntime.Client) *FolderMetadataManager {
	return &FolderMetadataManager{session: session}
}

// FolderMetadataListFolderMetadataOptions carries the optional parameters.
type FolderMetadataListFolderMetadataOptions struct {
	View *string
}

func (m *FolderMetadataManager) ListFolderMetadata(ctx context.Context, folderId string, opts *FolderMetadataListFolderMetadataOptions) (*schemas.Metadatas, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata")
	if opts != nil {
		if opts.View != nil {
			req = gantryruntime.WithQuery(req, "view", (*opts.View))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Metadatas)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderMetadataManager) GetFolderMetadata(ctx context.Context, folderId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderMetadataManager) UpdateFolderMetadata(ctx context.Context, folderId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, body []schemas.FileMetadataUpdateRequest) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderMetadataManager) CreateFolderMetadata(ctx context.Context, folderId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, body map[string]any) (*schemas.MetadataFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderMetadataManager) DeleteFolderMetadata(ctx context.Context, folderId string, scope schemas.GetFileIdMetadataIdIdScope, templateKey string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
