// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FolderClassificationsManager groups the "folder_classifications" operations.
type FolderClassificationsManager struct {
	session *gantryruntime.Client
}

// NewFolderClassificationsManager builds the manager against a runtime session.
func NewFolderClassificationsManager(session *gantryruntime.Client) *FolderClassificationsManager {
	return &FolderClassificationsManager{session: session}
}

func (m *FolderClassificationsManager) Get(ctx context.Context, folderId string) (*schemas.Classification, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderClassificationsManager) Update(ctx context.Context, folderId string, body []schemas.FileClassificationUpdateRequest) (*schemas.Classification, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderClassificationsManager) Create(ctx context.Context, folderId string, body *schemas.FileClassificationCreateRequest) (*schemas.Classification, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Classification)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderClassificationsManager) Delete(ctx context.Context, folderId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/metadata"+"/enterprise"+"/securityClassification-6VMVochwUWo")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
