// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// FolderLocksManager groups the "folder_locks" operations.
type FolderLocksManager struct {
	session *gantryruntime.Client
}

// NewFolderLocksManager builds the manager against a runtime session.
func NewFolderLocksManager(session *gantryruntime.Client) *FolderLocksManager {
	return &FolderLocksManager{session: session}
}

func (m *FolderLocksManager) List(ctx context.Context, folderId string) (*schemas.FolderLocks, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folder_locks")
	req = gantryruntime.WithQuery(req, "folder_id", folderId)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderLocks)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderLocksManager) Create(ctx context.Context, body *schemas.FolderLockCreateRequest) (*schemas.FolderLock, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folder_locks")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderLock)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *FolderLocksManager) Delete(ctx context.Context, folderLockId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/folder_locks"+"/"+url.PathEscape(folderLockId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
