// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// GroupsManager groups the "groups" operations.
type GroupsManager struct {
	session *gantryruntime.Client
}

// NewGroupsManager builds the manager against a runtime session.
func NewGroupsManager(session *gantryruntime.Client) *GroupsManager {
	return &GroupsManager{session: session}
}

// GroupsListOptions carries the optional parameters.
type GroupsListOptions struct {
	FilterTerm *string
	Fields     []string
	Limit      *int64
	Offset     *int64
}

func (m *GroupsManager) listPage(ctx context.Context, opts *GroupsListOptions) (*schemas.Groups, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/groups")
	if opts != nil {
		if opts.FilterTerm != nil {
			req = gantryruntime.WithQuery(req, "filter_term", (*opts.FilterTerm))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Groups)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *GroupsManager) List(ctx context.Context, opts *GroupsListOptions) iter.Seq2[*schemas.GroupFull, error] {
	return func(yield func(*schemas.GroupFull, error) bool) {
		var o GroupsListOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// GroupsCreateOptions carries the optional parameters.
type GroupsCreateOptions struct {
	Fields []string
}

func (m *GroupsManager) Create(ctx context.Context, body *schemas.GroupCreateRequest, opts *GroupsCreateOptions) (*schemas.GroupFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/groups")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsGetOptions carries the optional parameters.
type GroupsGetOptions struct {
	Fields []string
}

func (m *GroupsManager) Get(ctx context.Context, groupId string, opts *GroupsGetOptions) (*schemas.GroupFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/groups"+"/"+url.PathEscape(groupId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsUpdateOptions carries the optional parameters.
type GroupsUpdateOptions struct {
	Fields []string
}

func (m *GroupsManager) Update(ctx context.Context, groupId string, body *schemas.GroupUpdateRequest, opts *GroupsUpdateOptions) (*schemas.GroupFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/groups"+"/"+url.PathEscape(groupId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *GroupsManager) Delete(ctx context.Context, groupId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/groups"+"/"+url.PathEscape(groupId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
