// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"strconv"
	"strings"
)

func joinStringLike[T ~string](values []T) string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = string(v)
	}
	return strings.Join(out, ",")
}

func joinInt64(values []int64) string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = strconv.FormatInt(v, 10)
	}
	return strings.Join(out, ",")
}
