// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// HubCollaborationsManager groups the "hub_collaborations" operations.
type HubCollaborationsManager struct {
	session *gantryruntime.Client
}

// NewHubCollaborationsManager builds the manager against a runtime session.
func NewHubCollaborationsManager(session *gantryruntime.Client) *HubCollaborationsManager {
	return &HubCollaborationsManager{session: session}
}

// HubCollaborationsListOptions carries the optional parameters.
type HubCollaborationsListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *HubCollaborationsManager) listPage(ctx context.Context, hubId string, opts *HubCollaborationsListOptions) (*schemas.HubCollaborations, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hub_collaborations")
	req = gantryruntime.WithQuery(req, "hub_id", hubId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubCollaborations)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubCollaborationsManager) List(ctx context.Context, hubId string, opts *HubCollaborationsListOptions) iter.Seq2[*schemas.HubCollaboration, error] {
	return func(yield func(*schemas.HubCollaboration, error) bool) {
		var o HubCollaborationsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, hubId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *HubCollaborationsManager) Create(ctx context.Context, body *schemas.HubCollaborationCreateRequest) (*schemas.HubCollaboration, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/hub_collaborations")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubCollaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubCollaborationsManager) Get(ctx context.Context, hubCollaborationId string) (*schemas.HubCollaboration, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hub_collaborations"+"/"+url.PathEscape(hubCollaborationId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubCollaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubCollaborationsManager) Update(ctx context.Context, hubCollaborationId string, body *schemas.HubCollaborationUpdateRequest) (*schemas.HubCollaboration, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/hub_collaborations"+"/"+url.PathEscape(hubCollaborationId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubCollaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubCollaborationsManager) Delete(ctx context.Context, hubCollaborationId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/hub_collaborations"+"/"+url.PathEscape(hubCollaborationId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
