// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// HubItemsManager groups the "hub_items" operations.
type HubItemsManager struct {
	session *gantryruntime.Client
}

// NewHubItemsManager builds the manager against a runtime session.
func NewHubItemsManager(session *gantryruntime.Client) *HubItemsManager {
	return &HubItemsManager{session: session}
}

// HubItemsListOptions carries the optional parameters.
type HubItemsListOptions struct {
	ParentId *string
	Marker   *string
	Limit    *int64
}

func (m *HubItemsManager) listPage(ctx context.Context, hubId string, opts *HubItemsListOptions) (*schemas.HubItems, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hub_items")
	req = gantryruntime.WithQuery(req, "hub_id", hubId)
	if opts != nil {
		if opts.ParentId != nil {
			req = gantryruntime.WithQuery(req, "parent_id", (*opts.ParentId))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubItems)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubItemsManager) List(ctx context.Context, hubId string, opts *HubItemsListOptions) iter.Seq2[*schemas.HubItem, error] {
	return func(yield func(*schemas.HubItem, error) bool) {
		var o HubItemsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, hubId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *HubItemsManager) CreateHubManageItems(ctx context.Context, hubId string, body *schemas.HubItemsManageRequest) (*schemas.HubItemsManageResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/hubs"+"/"+url.PathEscape(hubId)+"/manage_items")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubItemsManageResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
