// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"strconv"
)

// HubDocumentManager groups the "hub_document" operations.
type HubDocumentManager struct {
	session *gantryruntime.Client
}

// NewHubDocumentManager builds the manager against a runtime session.
func NewHubDocumentManager(session *gantryruntime.Client) *HubDocumentManager {
	return &HubDocumentManager{session: session}
}

// HubDocumentListPagesOptions carries the optional parameters.
type HubDocumentListPagesOptions struct {
	Marker *string
	Limit  *int64
}

func (m *HubDocumentManager) listPagesPage(ctx context.Context, hubId string, opts *HubDocumentListPagesOptions) (*schemas.HubDocumentPages, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hub_document_pages")
	req = gantryruntime.WithQuery(req, "hub_id", hubId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubDocumentPages)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubDocumentManager) ListPages(ctx context.Context, hubId string, opts *HubDocumentListPagesOptions) iter.Seq2[*schemas.HubDocumentPage, error] {
	return func(yield func(*schemas.HubDocumentPage, error) bool) {
		var o HubDocumentListPagesOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPagesPage(ctx, hubId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// HubDocumentListBlocksOptions carries the optional parameters.
type HubDocumentListBlocksOptions struct {
	Marker *string
	Limit  *int64
}

func (m *HubDocumentManager) listBlocksPage(ctx context.Context, hubId string, pageId string, opts *HubDocumentListBlocksOptions) (*schemas.HubDocumentBlocks, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hub_document_blocks")
	req = gantryruntime.WithQuery(req, "hub_id", hubId)
	req = gantryruntime.WithQuery(req, "page_id", pageId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.HubDocumentBlocks)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubDocumentManager) ListBlocks(ctx context.Context, hubId string, pageId string, opts *HubDocumentListBlocksOptions) iter.Seq2[*schemas.HubDocumentBlockEntry, error] {
	return func(yield func(*schemas.HubDocumentBlockEntry, error) bool) {
		var o HubDocumentListBlocksOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listBlocksPage(ctx, hubId, pageId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
