// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// HubsManager groups the "hubs" operations.
type HubsManager struct {
	session *gantryruntime.Client
}

// NewHubsManager builds the manager against a runtime session.
func NewHubsManager(session *gantryruntime.Client) *HubsManager {
	return &HubsManager{session: session}
}

// HubsListOptions carries the optional parameters.
type HubsListOptions struct {
	Query     *string
	Scope     *string
	Sort      *string
	Direction *schemas.GetDirection
	Marker    *string
	Limit     *int64
}

func (m *HubsManager) listPage(ctx context.Context, opts *HubsListOptions) (*schemas.Hubs, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hubs")
	if opts != nil {
		if opts.Query != nil {
			req = gantryruntime.WithQuery(req, "query", (*opts.Query))
		}
		if opts.Scope != nil {
			req = gantryruntime.WithQuery(req, "scope", (*opts.Scope))
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", (*opts.Sort))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hubs)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubsManager) List(ctx context.Context, opts *HubsListOptions) iter.Seq2[*schemas.Hub, error] {
	return func(yield func(*schemas.Hub, error) bool) {
		var o HubsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *HubsManager) Create(ctx context.Context, body *schemas.HubCreateRequest) (*schemas.Hub, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/hubs")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hub)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// HubsListEnterpriseOptions carries the optional parameters.
type HubsListEnterpriseOptions struct {
	Query     *string
	Sort      *string
	Direction *schemas.GetDirection
	Marker    *string
	Limit     *int64
}

func (m *HubsManager) listEnterprisePage(ctx context.Context, opts *HubsListEnterpriseOptions) (*schemas.Hubs, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/enterprise_hubs")
	if opts != nil {
		if opts.Query != nil {
			req = gantryruntime.WithQuery(req, "query", (*opts.Query))
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", (*opts.Sort))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hubs)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubsManager) ListEnterprise(ctx context.Context, opts *HubsListEnterpriseOptions) iter.Seq2[*schemas.Hub, error] {
	return func(yield func(*schemas.Hub, error) bool) {
		var o HubsListEnterpriseOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listEnterprisePage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *HubsManager) Get(ctx context.Context, hubId string) (*schemas.Hub, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/hubs"+"/"+url.PathEscape(hubId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hub)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubsManager) Update(ctx context.Context, hubId string, body *schemas.HubUpdateRequest) (*schemas.Hub, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/hubs"+"/"+url.PathEscape(hubId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hub)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *HubsManager) Delete(ctx context.Context, hubId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/hubs"+"/"+url.PathEscape(hubId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *HubsManager) Copy(ctx context.Context, hubId string, body *schemas.HubCopyRequest) (*schemas.Hub, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/hubs"+"/"+url.PathEscape(hubId)+"/copy")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Hub)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
