// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// IntegrationMappingsManager groups the "integration_mappings" operations.
type IntegrationMappingsManager struct {
	session *gantryruntime.Client
}

// NewIntegrationMappingsManager builds the manager against a runtime session.
func NewIntegrationMappingsManager(session *gantryruntime.Client) *IntegrationMappingsManager {
	return &IntegrationMappingsManager{session: session}
}

// IntegrationMappingsListSlackOptions carries the optional parameters.
type IntegrationMappingsListSlackOptions struct {
	Marker            *string
	Limit             *int64
	PartnerItemType   *schemas.IntegrationMappingPartnerItemSlackType
	PartnerItemId     *string
	BoxItemId         *string
	BoxItemType       *schemas.FolderType
	IsManuallyCreated *bool
}

func (m *IntegrationMappingsManager) listSlackPage(ctx context.Context, opts *IntegrationMappingsListSlackOptions) (*schemas.IntegrationMappings, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/integration_mappings"+"/slack")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.PartnerItemType != nil {
			req = gantryruntime.WithQuery(req, "partner_item_type", string((*opts.PartnerItemType)))
		}
		if opts.PartnerItemId != nil {
			req = gantryruntime.WithQuery(req, "partner_item_id", (*opts.PartnerItemId))
		}
		if opts.BoxItemId != nil {
			req = gantryruntime.WithQuery(req, "box_item_id", (*opts.BoxItemId))
		}
		if opts.BoxItemType != nil {
			req = gantryruntime.WithQuery(req, "box_item_type", string((*opts.BoxItemType)))
		}
		if opts.IsManuallyCreated != nil {
			req = gantryruntime.WithQuery(req, "is_manually_created", strconv.FormatBool((*opts.IsManuallyCreated)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMappings)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) ListSlack(ctx context.Context, opts *IntegrationMappingsListSlackOptions) iter.Seq2[*schemas.IntegrationMapping, error] {
	return func(yield func(*schemas.IntegrationMapping, error) bool) {
		var o IntegrationMappingsListSlackOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listSlackPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *IntegrationMappingsManager) CreateSlack(ctx context.Context, body *schemas.IntegrationMappingSlackCreateRequest) (*schemas.IntegrationMapping, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/integration_mappings"+"/slack")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMapping)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) UpdateSlack(ctx context.Context, integrationMappingId string, body *schemas.SlackUpdateRequest) (*schemas.IntegrationMapping, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/integration_mappings"+"/slack"+"/"+url.PathEscape(integrationMappingId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMapping)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) DeleteSlack(ctx context.Context, integrationMappingId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/integration_mappings"+"/slack"+"/"+url.PathEscape(integrationMappingId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// IntegrationMappingsListTeamsOptions carries the optional parameters.
type IntegrationMappingsListTeamsOptions struct {
	PartnerItemType *schemas.IntegrationMappingPartnerItemTeamsType
	PartnerItemId   *string
	BoxItemId       *string
	BoxItemType     *schemas.FolderType
}

func (m *IntegrationMappingsManager) ListTeams(ctx context.Context, opts *IntegrationMappingsListTeamsOptions) (*schemas.IntegrationMappingsTeams, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/integration_mappings"+"/teams")
	if opts != nil {
		if opts.PartnerItemType != nil {
			req = gantryruntime.WithQuery(req, "partner_item_type", string((*opts.PartnerItemType)))
		}
		if opts.PartnerItemId != nil {
			req = gantryruntime.WithQuery(req, "partner_item_id", (*opts.PartnerItemId))
		}
		if opts.BoxItemId != nil {
			req = gantryruntime.WithQuery(req, "box_item_id", (*opts.BoxItemId))
		}
		if opts.BoxItemType != nil {
			req = gantryruntime.WithQuery(req, "box_item_type", string((*opts.BoxItemType)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMappingsTeams)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) CreateTeams(ctx context.Context, body *schemas.IntegrationMappingTeamsCreateRequest) (*schemas.IntegrationMappingTeams, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/integration_mappings"+"/teams")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMappingTeams)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) UpdateTeam(ctx context.Context, integrationMappingId string, body *schemas.TeamUpdateRequest) (*schemas.IntegrationMappingTeams, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/integration_mappings"+"/teams"+"/"+url.PathEscape(integrationMappingId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.IntegrationMappingTeams)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *IntegrationMappingsManager) DeleteTeam(ctx context.Context, integrationMappingId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/integration_mappings"+"/teams"+"/"+url.PathEscape(integrationMappingId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
