// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// InvitesManager groups the "invites" operations.
type InvitesManager struct {
	session *gantryruntime.Client
}

// NewInvitesManager builds the manager against a runtime session.
func NewInvitesManager(session *gantryruntime.Client) *InvitesManager {
	return &InvitesManager{session: session}
}

// InvitesCreateOptions carries the optional parameters.
type InvitesCreateOptions struct {
	Fields []string
}

func (m *InvitesManager) Create(ctx context.Context, body *schemas.InviteCreateRequest, opts *InvitesCreateOptions) (*schemas.Invite, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/invites")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Invite)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// InvitesGetOptions carries the optional parameters.
type InvitesGetOptions struct {
	Fields []string
}

func (m *InvitesManager) Get(ctx context.Context, inviteId string, opts *InvitesGetOptions) (*schemas.Invite, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/invites"+"/"+url.PathEscape(inviteId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Invite)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
