// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// LegalHoldPoliciesManager groups the "legal_hold_policies" operations.
type LegalHoldPoliciesManager struct {
	session *gantryruntime.Client
}

// NewLegalHoldPoliciesManager builds the manager against a runtime session.
func NewLegalHoldPoliciesManager(session *gantryruntime.Client) *LegalHoldPoliciesManager {
	return &LegalHoldPoliciesManager{session: session}
}

// LegalHoldPoliciesListOptions carries the optional parameters.
type LegalHoldPoliciesListOptions struct {
	PolicyName *string
	Fields     []string
	Marker     *string
	Limit      *int64
}

func (m *LegalHoldPoliciesManager) listPage(ctx context.Context, opts *LegalHoldPoliciesListOptions) (*schemas.LegalHoldPolicies, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policies")
	if opts != nil {
		if opts.PolicyName != nil {
			req = gantryruntime.WithQuery(req, "policy_name", (*opts.PolicyName))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicies)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPoliciesManager) List(ctx context.Context, opts *LegalHoldPoliciesListOptions) iter.Seq2[*schemas.LegalHoldPolicy, error] {
	return func(yield func(*schemas.LegalHoldPolicy, error) bool) {
		var o LegalHoldPoliciesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *LegalHoldPoliciesManager) Create(ctx context.Context, body *schemas.LegalHoldPolicyCreateRequest) (*schemas.LegalHoldPolicy, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/legal_hold_policies")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPoliciesManager) Get(ctx context.Context, legalHoldPolicyId string) (*schemas.LegalHoldPolicy, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policies"+"/"+url.PathEscape(legalHoldPolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPoliciesManager) Update(ctx context.Context, legalHoldPolicyId string, body *schemas.LegalHoldPolicyUpdateRequest) (*schemas.LegalHoldPolicy, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/legal_hold_policies"+"/"+url.PathEscape(legalHoldPolicyId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPoliciesManager) Delete(ctx context.Context, legalHoldPolicyId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/legal_hold_policies"+"/"+url.PathEscape(legalHoldPolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
