// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// LegalHoldPolicyAssignmentsManager groups the "legal_hold_policy_assignments" operations.
type LegalHoldPolicyAssignmentsManager struct {
	session *gantryruntime.Client
}

// NewLegalHoldPolicyAssignmentsManager builds the manager against a runtime session.
func NewLegalHoldPolicyAssignmentsManager(session *gantryruntime.Client) *LegalHoldPolicyAssignmentsManager {
	return &LegalHoldPolicyAssignmentsManager{session: session}
}

// LegalHoldPolicyAssignmentsListOptions carries the optional parameters.
type LegalHoldPolicyAssignmentsListOptions struct {
	AssignToType *schemas.LegalHoldPolicyAssignedItemType
	AssignToId   *string
	Marker       *string
	Limit        *int64
	Fields       []string
}

func (m *LegalHoldPolicyAssignmentsManager) listPage(ctx context.Context, policyId string, opts *LegalHoldPolicyAssignmentsListOptions) (*schemas.LegalHoldPolicyAssignments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policy_assignments")
	req = gantryruntime.WithQuery(req, "policy_id", policyId)
	if opts != nil {
		if opts.AssignToType != nil {
			req = gantryruntime.WithQuery(req, "assign_to_type", string((*opts.AssignToType)))
		}
		if opts.AssignToId != nil {
			req = gantryruntime.WithQuery(req, "assign_to_id", (*opts.AssignToId))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicyAssignments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPolicyAssignmentsManager) List(ctx context.Context, policyId string, opts *LegalHoldPolicyAssignmentsListOptions) iter.Seq2[*schemas.LegalHoldPolicyAssignment, error] {
	return func(yield func(*schemas.LegalHoldPolicyAssignment, error) bool) {
		var o LegalHoldPolicyAssignmentsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, policyId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *LegalHoldPolicyAssignmentsManager) Create(ctx context.Context, body *schemas.LegalHoldPolicyAssignmentCreateRequest) (*schemas.LegalHoldPolicyAssignment, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/legal_hold_policy_assignments")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPolicyAssignmentsManager) Get(ctx context.Context, legalHoldPolicyAssignmentId string) (*schemas.LegalHoldPolicyAssignment, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policy_assignments"+"/"+url.PathEscape(legalHoldPolicyAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.LegalHoldPolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPolicyAssignmentsManager) Delete(ctx context.Context, legalHoldPolicyAssignmentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/legal_hold_policy_assignments"+"/"+url.PathEscape(legalHoldPolicyAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// LegalHoldPolicyAssignmentsListFileOnHoldOptions carries the optional parameters.
type LegalHoldPolicyAssignmentsListFileOnHoldOptions struct {
	Marker *string
	Limit  *int64
	Fields []string
}

func (m *LegalHoldPolicyAssignmentsManager) listFileOnHoldPage(ctx context.Context, legalHoldPolicyAssignmentId string, opts *LegalHoldPolicyAssignmentsListFileOnHoldOptions) (*schemas.FilesOnHold, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policy_assignments"+"/"+url.PathEscape(legalHoldPolicyAssignmentId)+"/files_on_hold")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FilesOnHold)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPolicyAssignmentsManager) ListFileOnHold(ctx context.Context, legalHoldPolicyAssignmentId string, opts *LegalHoldPolicyAssignmentsListFileOnHoldOptions) iter.Seq2[*schemas.FileMini, error] {
	return func(yield func(*schemas.FileMini, error) bool) {
		var o LegalHoldPolicyAssignmentsListFileOnHoldOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFileOnHoldPage(ctx, legalHoldPolicyAssignmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// LegalHoldPolicyAssignmentsListFileVersionOnHoldOptions carries the optional parameters.
type LegalHoldPolicyAssignmentsListFileVersionOnHoldOptions struct {
	Marker *string
	Limit  *int64
	Fields []string
}

func (m *LegalHoldPolicyAssignmentsManager) listFileVersionOnHoldPage(ctx context.Context, legalHoldPolicyAssignmentId string, opts *LegalHoldPolicyAssignmentsListFileVersionOnHoldOptions) (*schemas.FileVersionsOnHold, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/legal_hold_policy_assignments"+"/"+url.PathEscape(legalHoldPolicyAssignmentId)+"/file_versions_on_hold")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileVersionsOnHold)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *LegalHoldPolicyAssignmentsManager) ListFileVersionOnHold(ctx context.Context, legalHoldPolicyAssignmentId string, opts *LegalHoldPolicyAssignmentsListFileVersionOnHoldOptions) iter.Seq2[*schemas.FileVersion, error] {
	return func(yield func(*schemas.FileVersion, error) bool) {
		var o LegalHoldPolicyAssignmentsListFileVersionOnHoldOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFileVersionOnHoldPage(ctx, legalHoldPolicyAssignmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
