// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// ListCollaborationsManager groups the "list_collaborations" operations.
type ListCollaborationsManager struct {
	session *gantryruntime.Client
}

// NewListCollaborationsManager builds the manager against a runtime session.
func NewListCollaborationsManager(session *gantryruntime.Client) *ListCollaborationsManager {
	return &ListCollaborationsManager{session: session}
}

// ListCollaborationsListFileCollaborationsOptions carries the optional parameters.
type ListCollaborationsListFileCollaborationsOptions struct {
	Fields []string
	Limit  *int64
	Marker *string
}

func (m *ListCollaborationsManager) listFileCollaborationsPage(ctx context.Context, fileId string, opts *ListCollaborationsListFileCollaborationsOptions) (*schemas.Collaborations, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/collaborations")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collaborations)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ListCollaborationsManager) ListFileCollaborations(ctx context.Context, fileId string, opts *ListCollaborationsListFileCollaborationsOptions) iter.Seq2[*schemas.Collaboration, error] {
	return func(yield func(*schemas.Collaboration, error) bool) {
		var o ListCollaborationsListFileCollaborationsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFileCollaborationsPage(ctx, fileId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// ListCollaborationsListFolderCollaborationsOptions carries the optional parameters.
type ListCollaborationsListFolderCollaborationsOptions struct {
	Fields []string
	Limit  *int64
	Marker *string
}

func (m *ListCollaborationsManager) listFolderCollaborationsPage(ctx context.Context, folderId string, opts *ListCollaborationsListFolderCollaborationsOptions) (*schemas.Collaborations, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/collaborations")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collaborations)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ListCollaborationsManager) ListFolderCollaborations(ctx context.Context, folderId string, opts *ListCollaborationsListFolderCollaborationsOptions) iter.Seq2[*schemas.Collaboration, error] {
	return func(yield func(*schemas.Collaboration, error) bool) {
		var o ListCollaborationsListFolderCollaborationsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFolderCollaborationsPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// ListCollaborationsListCollaborationsOptions carries the optional parameters.
type ListCollaborationsListCollaborationsOptions struct {
	Fields []string
	Offset *int64
	Limit  *int64
}

func (m *ListCollaborationsManager) listCollaborationsPage(ctx context.Context, status schemas.GetCollaborationsStatus, opts *ListCollaborationsListCollaborationsOptions) (*schemas.CollaborationsOffsetPaginated, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaborations")
	req = gantryruntime.WithQuery(req, "status", string(status))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationsOffsetPaginated)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ListCollaborationsManager) ListCollaborations(ctx context.Context, status schemas.GetCollaborationsStatus, opts *ListCollaborationsListCollaborationsOptions) iter.Seq2[*schemas.Collaboration, error] {
	return func(yield func(*schemas.Collaboration, error) bool) {
		var o ListCollaborationsListCollaborationsOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listCollaborationsPage(ctx, status, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// ListCollaborationsListGroupCollaborationsOptions carries the optional parameters.
type ListCollaborationsListGroupCollaborationsOptions struct {
	Limit  *int64
	Offset *int64
}

func (m *ListCollaborationsManager) listGroupCollaborationsPage(ctx context.Context, groupId string, opts *ListCollaborationsListGroupCollaborationsOptions) (*schemas.CollaborationsOffsetPaginated, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/groups"+"/"+url.PathEscape(groupId)+"/collaborations")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.CollaborationsOffsetPaginated)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ListCollaborationsManager) ListGroupCollaborations(ctx context.Context, groupId string, opts *ListCollaborationsListGroupCollaborationsOptions) iter.Seq2[*schemas.Collaboration, error] {
	return func(yield func(*schemas.Collaboration, error) bool) {
		var o ListCollaborationsListGroupCollaborationsOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listGroupCollaborationsPage(ctx, groupId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}
