// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// MembershipsManager groups the "memberships" operations.
type MembershipsManager struct {
	session *gantryruntime.Client
}

// NewMembershipsManager builds the manager against a runtime session.
func NewMembershipsManager(session *gantryruntime.Client) *MembershipsManager {
	return &MembershipsManager{session: session}
}

// MembershipsListUserOptions carries the optional parameters.
type MembershipsListUserOptions struct {
	Limit  *int64
	Offset *int64
}

func (m *MembershipsManager) listUserPage(ctx context.Context, userId string, opts *MembershipsListUserOptions) (*schemas.GroupMemberships, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/memberships")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupMemberships)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MembershipsManager) ListUser(ctx context.Context, userId string, opts *MembershipsListUserOptions) iter.Seq2[*schemas.GroupMembership, error] {
	return func(yield func(*schemas.GroupMembership, error) bool) {
		var o MembershipsListUserOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listUserPage(ctx, userId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// MembershipsListGroupOptions carries the optional parameters.
type MembershipsListGroupOptions struct {
	Limit  *int64
	Offset *int64
}

func (m *MembershipsManager) listGroupPage(ctx context.Context, groupId string, opts *MembershipsListGroupOptions) (*schemas.GroupMemberships, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/groups"+"/"+url.PathEscape(groupId)+"/memberships")
	if opts != nil {
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupMemberships)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MembershipsManager) ListGroup(ctx context.Context, groupId string, opts *MembershipsListGroupOptions) iter.Seq2[*schemas.GroupMembership, error] {
	return func(yield func(*schemas.GroupMembership, error) bool) {
		var o MembershipsListGroupOptions
		if opts != nil {
			o = *opts
		}
		var offset int64
		if o.Offset != nil {
			offset = *o.Offset
		}
		for {
			o.Offset = &offset
			page, err := m.listGroupPage(ctx, groupId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if len(page.Entries) == 0 {
				return
			}
			offset += int64(len(page.Entries))
		}
	}
}

// MembershipsCreateGroupOptions carries the optional parameters.
type MembershipsCreateGroupOptions struct {
	Fields []string
}

func (m *MembershipsManager) CreateGroup(ctx context.Context, body *schemas.GroupCreateRequest2, opts *MembershipsCreateGroupOptions) (*schemas.GroupMembership, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/group_memberships")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupMembership)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipsGetGroupOptions carries the optional parameters.
type MembershipsGetGroupOptions struct {
	Fields []string
}

func (m *MembershipsManager) GetGroup(ctx context.Context, groupMembershipId string, opts *MembershipsGetGroupOptions) (*schemas.GroupMembership, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/group_memberships"+"/"+url.PathEscape(groupMembershipId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupMembership)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipsUpdateGroupOptions carries the optional parameters.
type MembershipsUpdateGroupOptions struct {
	Fields []string
}

func (m *MembershipsManager) UpdateGroup(ctx context.Context, groupMembershipId string, body *schemas.GroupUpdateRequest2, opts *MembershipsUpdateGroupOptions) (*schemas.GroupMembership, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/group_memberships"+"/"+url.PathEscape(groupMembershipId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.GroupMembership)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MembershipsManager) DeleteGroup(ctx context.Context, groupMembershipId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/group_memberships"+"/"+url.PathEscape(groupMembershipId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
