// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// MetadataCascadePoliciesManager groups the "metadata_cascade_policies" operations.
type MetadataCascadePoliciesManager struct {
	session *gantryruntime.Client
}

// NewMetadataCascadePoliciesManager builds the manager against a runtime session.
func NewMetadataCascadePoliciesManager(session *gantryruntime.Client) *MetadataCascadePoliciesManager {
	return &MetadataCascadePoliciesManager{session: session}
}

// MetadataCascadePoliciesListOptions carries the optional parameters.
type MetadataCascadePoliciesListOptions struct {
	OwnerEnterpriseId *string
	Marker            *string
	Offset            *int64
}

func (m *MetadataCascadePoliciesManager) listPage(ctx context.Context, folderId string, opts *MetadataCascadePoliciesListOptions) (*schemas.MetadataCascadePolicies, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_cascade_policies")
	req = gantryruntime.WithQuery(req, "folder_id", folderId)
	if opts != nil {
		if opts.OwnerEnterpriseId != nil {
			req = gantryruntime.WithQuery(req, "owner_enterprise_id", (*opts.OwnerEnterpriseId))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataCascadePolicies)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataCascadePoliciesManager) List(ctx context.Context, folderId string, opts *MetadataCascadePoliciesListOptions) iter.Seq2[*schemas.MetadataCascadePolicy, error] {
	return func(yield func(*schemas.MetadataCascadePolicy, error) bool) {
		var o MetadataCascadePoliciesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *MetadataCascadePoliciesManager) Create(ctx context.Context, body *schemas.MetadataCascadePolicyCreateRequest) (*schemas.MetadataCascadePolicy, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_cascade_policies")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataCascadePolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataCascadePoliciesManager) Get(ctx context.Context, metadataCascadePolicyId string) (*schemas.MetadataCascadePolicy, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_cascade_policies"+"/"+url.PathEscape(metadataCascadePolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataCascadePolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataCascadePoliciesManager) Delete(ctx context.Context, metadataCascadePolicyId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/metadata_cascade_policies"+"/"+url.PathEscape(metadataCascadePolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *MetadataCascadePoliciesManager) Apply(ctx context.Context, metadataCascadePolicyId string, body *schemas.MetadataCascadePolicyApplyRequest) error {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_cascade_policies"+"/"+url.PathEscape(metadataCascadePolicyId)+"/apply")
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
