// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// MetadataTemplatesManager groups the "metadata_templates" operations.
type MetadataTemplatesManager struct {
	session *gantryruntime.Client
}

// NewMetadataTemplatesManager builds the manager against a runtime session.
func NewMetadataTemplatesManager(session *gantryruntime.Client) *MetadataTemplatesManager {
	return &MetadataTemplatesManager{session: session}
}

// MetadataTemplatesListOptions carries the optional parameters.
type MetadataTemplatesListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *MetadataTemplatesManager) listPage(ctx context.Context, metadataInstanceId string, opts *MetadataTemplatesListOptions) (*schemas.MetadataTemplates, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates")
	req = gantryruntime.WithQuery(req, "metadata_instance_id", metadataInstanceId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplates)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTemplatesManager) List(ctx context.Context, metadataInstanceId string, opts *MetadataTemplatesListOptions) iter.Seq2[*schemas.MetadataTemplate, error] {
	return func(yield func(*schemas.MetadataTemplate, error) bool) {
		var o MetadataTemplatesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, metadataInstanceId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *MetadataTemplatesManager) GetSchema(ctx context.Context, scope schemas.GetFileIdMetadataIdIdScope, templateKey string) (*schemas.MetadataTemplate, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey)+"/schema")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTemplatesManager) UpdateSchema(ctx context.Context, scope schemas.GetFileIdMetadataIdIdScope, templateKey string, body []schemas.SchemaUpdateRequest) (*schemas.MetadataTemplate, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/metadata_templates"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey)+"/schema")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTemplatesManager) DeleteSchema(ctx context.Context, scope schemas.GetFileIdMetadataIdIdScope, templateKey string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/metadata_templates"+"/"+url.PathEscape(string(scope))+"/"+url.PathEscape(templateKey)+"/schema")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *MetadataTemplatesManager) Get(ctx context.Context, templateId string) (*schemas.MetadataTemplate, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/"+url.PathEscape(templateId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataTemplatesListGlobalOptions carries the optional parameters.
type MetadataTemplatesListGlobalOptions struct {
	Marker *string
	Limit  *int64
}

func (m *MetadataTemplatesManager) listGlobalPage(ctx context.Context, opts *MetadataTemplatesListGlobalOptions) (*schemas.MetadataTemplates, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/global")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplates)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTemplatesManager) ListGlobal(ctx context.Context, opts *MetadataTemplatesListGlobalOptions) iter.Seq2[*schemas.MetadataTemplate, error] {
	return func(yield func(*schemas.MetadataTemplate, error) bool) {
		var o MetadataTemplatesListGlobalOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listGlobalPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// MetadataTemplatesListEnterpriseOptions carries the optional parameters.
type MetadataTemplatesListEnterpriseOptions struct {
	Marker *string
	Limit  *int64
}

func (m *MetadataTemplatesManager) listEnterprisePage(ctx context.Context, opts *MetadataTemplatesListEnterpriseOptions) (*schemas.MetadataTemplates, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/enterprise")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplates)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTemplatesManager) ListEnterprise(ctx context.Context, opts *MetadataTemplatesListEnterpriseOptions) iter.Seq2[*schemas.MetadataTemplate, error] {
	return func(yield func(*schemas.MetadataTemplate, error) bool) {
		var o MetadataTemplatesListEnterpriseOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listEnterprisePage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *MetadataTemplatesManager) CreateSchema(ctx context.Context, body *schemas.SchemaCreateRequest) (*schemas.MetadataTemplate, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_templates"+"/schema")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
