// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// MetadataTaxonomiesManager groups the "metadata_taxonomies" operations.
type MetadataTaxonomiesManager struct {
	session *gantryruntime.Client
}

// NewMetadataTaxonomiesManager builds the manager against a runtime session.
func NewMetadataTaxonomiesManager(session *gantryruntime.Client) *MetadataTaxonomiesManager {
	return &MetadataTaxonomiesManager{session: session}
}

func (m *MetadataTaxonomiesManager) Create(ctx context.Context, body *schemas.MetadataTaxonomyCreateRequest) (*schemas.MetadataTaxonomy, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_taxonomies")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataTaxonomiesListOptions carries the optional parameters.
type MetadataTaxonomiesListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *MetadataTaxonomiesManager) listPage(ctx context.Context, namespace string, opts *MetadataTaxonomiesListOptions) (*schemas.MetadataTaxonomies, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace))
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomies)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) List(ctx context.Context, namespace string, opts *MetadataTaxonomiesListOptions) iter.Seq2[*schemas.MetadataTaxonomy, error] {
	return func(yield func(*schemas.MetadataTaxonomy, error) bool) {
		var o MetadataTaxonomiesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, namespace, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *MetadataTaxonomiesManager) Get(ctx context.Context, namespace string, taxonomyKey string) (*schemas.MetadataTaxonomy, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) Delete(ctx context.Context, namespace string, taxonomyKey string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *MetadataTaxonomiesManager) Update(ctx context.Context, namespace string, taxonomyKey string, body *schemas.MetadataTaxonomyUpdateRequest) (*schemas.MetadataTaxonomy, error) {
	req := m.session.NewRequest("PATCH", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) CreateLevels(ctx context.Context, namespace string, taxonomyKey string, body []schemas.MetadataTaxonomyLevel) (*schemas.MetadataTaxonomyLevels, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/levels")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyLevels)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) UpdateLevel(ctx context.Context, namespace string, taxonomyKey string, levelIndex int64, body *schemas.LevelUpdateRequest) (*schemas.MetadataTaxonomyLevel, error) {
	req := m.session.NewRequest("PATCH", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/levels"+"/"+url.PathEscape(strconv.FormatInt(levelIndex, 10)))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyLevel)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) AppendLevels(ctx context.Context, namespace string, taxonomyKey string, body *schemas.LevelUpdateRequest) (*schemas.MetadataTaxonomyLevels, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/levels:append")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyLevels)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) TrimLevels(ctx context.Context, namespace string, taxonomyKey string) (*schemas.MetadataTaxonomyLevels, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/levels:trim")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyLevels)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataTaxonomiesListNodesOptions carries the optional parameters.
type MetadataTaxonomiesListNodesOptions struct {
	Level                   []int64
	Parent                  []string
	Ancestor                []string
	Query                   *string
	IncludeTotalResultCount *bool
	Marker                  *string
	Limit                   *int64
}

func (m *MetadataTaxonomiesManager) listNodesPage(ctx context.Context, namespace string, taxonomyKey string, opts *MetadataTaxonomiesListNodesOptions) (*schemas.MetadataTaxonomyNodes, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/nodes")
	if opts != nil {
		if opts.Level != nil {
			req = gantryruntime.WithQuery(req, "level", joinInt64(opts.Level))
		}
		if opts.Parent != nil {
			req = gantryruntime.WithQuery(req, "parent", strings.Join(opts.Parent, ","))
		}
		if opts.Ancestor != nil {
			req = gantryruntime.WithQuery(req, "ancestor", strings.Join(opts.Ancestor, ","))
		}
		if opts.Query != nil {
			req = gantryruntime.WithQuery(req, "query", (*opts.Query))
		}
		if opts.IncludeTotalResultCount != nil {
			req = gantryruntime.WithQuery(req, "include-total-result-count", strconv.FormatBool((*opts.IncludeTotalResultCount)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyNodes)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) ListNodes(ctx context.Context, namespace string, taxonomyKey string, opts *MetadataTaxonomiesListNodesOptions) iter.Seq2[*schemas.MetadataTaxonomyNode, error] {
	return func(yield func(*schemas.MetadataTaxonomyNode, error) bool) {
		var o MetadataTaxonomiesListNodesOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listNodesPage(ctx, namespace, taxonomyKey, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *MetadataTaxonomiesManager) CreateNodes(ctx context.Context, namespace string, taxonomyKey string, body *schemas.NodesCreateRequest) (*schemas.MetadataTaxonomyNode, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/nodes")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyNode)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) GetNode(ctx context.Context, namespace string, taxonomyKey string, nodeId string) (*schemas.MetadataTaxonomyNode, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/nodes"+"/"+url.PathEscape(nodeId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyNode)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) DeleteNode(ctx context.Context, namespace string, taxonomyKey string, nodeId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/nodes"+"/"+url.PathEscape(nodeId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *MetadataTaxonomiesManager) UpdateNode(ctx context.Context, namespace string, taxonomyKey string, nodeId string, body *schemas.NodeUpdateRequest) (*schemas.MetadataTaxonomyNode, error) {
	req := m.session.NewRequest("PATCH", m.session.BaseUrl("api")+"/metadata_taxonomies"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(taxonomyKey)+"/nodes"+"/"+url.PathEscape(nodeId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyNode)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataTaxonomiesListMetadataTemplateFieldOptionsOptions carries the optional parameters.
type MetadataTaxonomiesListMetadataTemplateFieldOptionsOptions struct {
	Level                   []int64
	Parent                  []string
	Ancestor                []string
	Query                   *string
	IncludeTotalResultCount *bool
	OnlySelectableOptions   *bool
	Marker                  *string
	Limit                   *int64
}

func (m *MetadataTaxonomiesManager) listMetadataTemplateFieldOptionsPage(ctx context.Context, namespace string, templateKey string, fieldKey string, opts *MetadataTaxonomiesListMetadataTemplateFieldOptionsOptions) (*schemas.MetadataTaxonomyNodes, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/metadata_templates"+"/"+url.PathEscape(namespace)+"/"+url.PathEscape(templateKey)+"/fields"+"/"+url.PathEscape(fieldKey)+"/options")
	if opts != nil {
		if opts.Level != nil {
			req = gantryruntime.WithQuery(req, "level", joinInt64(opts.Level))
		}
		if opts.Parent != nil {
			req = gantryruntime.WithQuery(req, "parent", strings.Join(opts.Parent, ","))
		}
		if opts.Ancestor != nil {
			req = gantryruntime.WithQuery(req, "ancestor", strings.Join(opts.Ancestor, ","))
		}
		if opts.Query != nil {
			req = gantryruntime.WithQuery(req, "query", (*opts.Query))
		}
		if opts.IncludeTotalResultCount != nil {
			req = gantryruntime.WithQuery(req, "include-total-result-count", strconv.FormatBool((*opts.IncludeTotalResultCount)))
		}
		if opts.OnlySelectableOptions != nil {
			req = gantryruntime.WithQuery(req, "only-selectable-options", strconv.FormatBool((*opts.OnlySelectableOptions)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataTaxonomyNodes)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *MetadataTaxonomiesManager) ListMetadataTemplateFieldOptions(ctx context.Context, namespace string, templateKey string, fieldKey string, opts *MetadataTaxonomiesListMetadataTemplateFieldOptionsOptions) iter.Seq2[*schemas.MetadataTaxonomyNode, error] {
	return func(yield func(*schemas.MetadataTaxonomyNode, error) bool) {
		var o MetadataTaxonomiesListMetadataTemplateFieldOptionsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listMetadataTemplateFieldOptionsPage(ctx, namespace, templateKey, fieldKey, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
