// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// NotesManager groups the "notes" operations.
type NotesManager struct {
	session *gantryruntime.Client
}

// NewNotesManager builds the manager against a runtime session.
func NewNotesManager(session *gantryruntime.Client) *NotesManager {
	return &NotesManager{session: session}
}

func (m *NotesManager) Convert(ctx context.Context, body *schemas.NotesConvertRequestBody) (*schemas.NotesConvertResponse, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/notes"+"/convert")
	req = gantryruntime.WithHeader(req, "box-version", "2026.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.NotesConvertResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
