// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"strconv"
	"strings"
)

// RecentItemsManager groups the "recent_items" operations.
type RecentItemsManager struct {
	session *gantryruntime.Client
}

// NewRecentItemsManager builds the manager against a runtime session.
func NewRecentItemsManager(session *gantryruntime.Client) *RecentItemsManager {
	return &RecentItemsManager{session: session}
}

// RecentItemsListOptions carries the optional parameters.
type RecentItemsListOptions struct {
	Fields []string
	Limit  *int64
	Marker *string
}

func (m *RecentItemsManager) listPage(ctx context.Context, opts *RecentItemsListOptions) (*schemas.RecentItems, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/recent_items")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RecentItems)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RecentItemsManager) List(ctx context.Context, opts *RecentItemsListOptions) iter.Seq2[*schemas.RecentItem, error] {
	return func(yield func(*schemas.RecentItem, error) bool) {
		var o RecentItemsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
