// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// RetentionPoliciesManager groups the "retention_policies" operations.
type RetentionPoliciesManager struct {
	session *gantryruntime.Client
}

// NewRetentionPoliciesManager builds the manager against a runtime session.
func NewRetentionPoliciesManager(session *gantryruntime.Client) *RetentionPoliciesManager {
	return &RetentionPoliciesManager{session: session}
}

// RetentionPoliciesListOptions carries the optional parameters.
type RetentionPoliciesListOptions struct {
	PolicyName      *string
	PolicyType      *schemas.RetentionPolicyPolicyType
	CreatedByUserId *string
	Fields          []string
	Limit           *int64
	Marker          *string
}

func (m *RetentionPoliciesManager) listPage(ctx context.Context, opts *RetentionPoliciesListOptions) (*schemas.RetentionPolicies, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policies")
	if opts != nil {
		if opts.PolicyName != nil {
			req = gantryruntime.WithQuery(req, "policy_name", (*opts.PolicyName))
		}
		if opts.PolicyType != nil {
			req = gantryruntime.WithQuery(req, "policy_type", string((*opts.PolicyType)))
		}
		if opts.CreatedByUserId != nil {
			req = gantryruntime.WithQuery(req, "created_by_user_id", (*opts.CreatedByUserId))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicies)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPoliciesManager) List(ctx context.Context, opts *RetentionPoliciesListOptions) iter.Seq2[*schemas.RetentionPolicy, error] {
	return func(yield func(*schemas.RetentionPolicy, error) bool) {
		var o RetentionPoliciesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *RetentionPoliciesManager) Create(ctx context.Context, body *schemas.RetentionPolicyCreateRequest) (*schemas.RetentionPolicy, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/retention_policies")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// RetentionPoliciesGetOptions carries the optional parameters.
type RetentionPoliciesGetOptions struct {
	Fields []string
}

func (m *RetentionPoliciesManager) Get(ctx context.Context, retentionPolicyId string, opts *RetentionPoliciesGetOptions) (*schemas.RetentionPolicy, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policies"+"/"+url.PathEscape(retentionPolicyId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPoliciesManager) Update(ctx context.Context, retentionPolicyId string, body *schemas.RetentionPolicyUpdateRequest) (*schemas.RetentionPolicy, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/retention_policies"+"/"+url.PathEscape(retentionPolicyId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPoliciesManager) Delete(ctx context.Context, retentionPolicyId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/retention_policies"+"/"+url.PathEscape(retentionPolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
