// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// RetentionPolicyAssignmentsManager groups the "retention_policy_assignments" operations.
type RetentionPolicyAssignmentsManager struct {
	session *gantryruntime.Client
}

// NewRetentionPolicyAssignmentsManager builds the manager against a runtime session.
func NewRetentionPolicyAssignmentsManager(session *gantryruntime.Client) *RetentionPolicyAssignmentsManager {
	return &RetentionPolicyAssignmentsManager{session: session}
}

// RetentionPolicyAssignmentsListRetentionPolicyAssignmentsOptions carries the optional parameters.
type RetentionPolicyAssignmentsListRetentionPolicyAssignmentsOptions struct {
	Type   *schemas.AssignedToType
	Fields []string
	Marker *string
	Limit  *int64
}

func (m *RetentionPolicyAssignmentsManager) listRetentionPolicyAssignmentsPage(ctx context.Context, retentionPolicyId string, opts *RetentionPolicyAssignmentsListRetentionPolicyAssignmentsOptions) (*schemas.RetentionPolicyAssignments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policies"+"/"+url.PathEscape(retentionPolicyId)+"/assignments")
	if opts != nil {
		if opts.Type != nil {
			req = gantryruntime.WithQuery(req, "type", string((*opts.Type)))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicyAssignments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPolicyAssignmentsManager) ListRetentionPolicyAssignments(ctx context.Context, retentionPolicyId string, opts *RetentionPolicyAssignmentsListRetentionPolicyAssignmentsOptions) iter.Seq2[*schemas.RetentionPolicyAssignment, error] {
	return func(yield func(*schemas.RetentionPolicyAssignment, error) bool) {
		var o RetentionPolicyAssignmentsListRetentionPolicyAssignmentsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listRetentionPolicyAssignmentsPage(ctx, retentionPolicyId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *RetentionPolicyAssignmentsManager) Create(ctx context.Context, body *schemas.RetentionPolicyAssignmentCreateRequest) (*schemas.RetentionPolicyAssignment, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/retention_policy_assignments")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// RetentionPolicyAssignmentsGetOptions carries the optional parameters.
type RetentionPolicyAssignmentsGetOptions struct {
	Fields []string
}

func (m *RetentionPolicyAssignmentsManager) Get(ctx context.Context, retentionPolicyAssignmentId string, opts *RetentionPolicyAssignmentsGetOptions) (*schemas.RetentionPolicyAssignment, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policy_assignments"+"/"+url.PathEscape(retentionPolicyAssignmentId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.RetentionPolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPolicyAssignmentsManager) Delete(ctx context.Context, retentionPolicyAssignmentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/retention_policy_assignments"+"/"+url.PathEscape(retentionPolicyAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// RetentionPolicyAssignmentsListFileUnderRetentionOptions carries the optional parameters.
type RetentionPolicyAssignmentsListFileUnderRetentionOptions struct {
	Marker *string
	Limit  *int64
}

func (m *RetentionPolicyAssignmentsManager) listFileUnderRetentionPage(ctx context.Context, retentionPolicyAssignmentId string, opts *RetentionPolicyAssignmentsListFileUnderRetentionOptions) (*schemas.FilesUnderRetention, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policy_assignments"+"/"+url.PathEscape(retentionPolicyAssignmentId)+"/files_under_retention")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FilesUnderRetention)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPolicyAssignmentsManager) ListFileUnderRetention(ctx context.Context, retentionPolicyAssignmentId string, opts *RetentionPolicyAssignmentsListFileUnderRetentionOptions) iter.Seq2[*schemas.FileMini, error] {
	return func(yield func(*schemas.FileMini, error) bool) {
		var o RetentionPolicyAssignmentsListFileUnderRetentionOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFileUnderRetentionPage(ctx, retentionPolicyAssignmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// RetentionPolicyAssignmentsListFileVersionUnderRetentionOptions carries the optional parameters.
type RetentionPolicyAssignmentsListFileVersionUnderRetentionOptions struct {
	Marker *string
	Limit  *int64
}

func (m *RetentionPolicyAssignmentsManager) listFileVersionUnderRetentionPage(ctx context.Context, retentionPolicyAssignmentId string, opts *RetentionPolicyAssignmentsListFileVersionUnderRetentionOptions) (*schemas.FilesUnderRetention, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/retention_policy_assignments"+"/"+url.PathEscape(retentionPolicyAssignmentId)+"/file_versions_under_retention")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FilesUnderRetention)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *RetentionPolicyAssignmentsManager) ListFileVersionUnderRetention(ctx context.Context, retentionPolicyAssignmentId string, opts *RetentionPolicyAssignmentsListFileVersionUnderRetentionOptions) iter.Seq2[*schemas.FileMini, error] {
	return func(yield func(*schemas.FileMini, error) bool) {
		var o RetentionPolicyAssignmentsListFileVersionUnderRetentionOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFileVersionUnderRetentionPage(ctx, retentionPolicyAssignmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
