// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"strconv"
	"strings"
)

// SearchManager groups the "search" operations.
type SearchManager struct {
	session *gantryruntime.Client
}

// NewSearchManager builds the manager against a runtime session.
func NewSearchManager(session *gantryruntime.Client) *SearchManager {
	return &SearchManager{session: session}
}

func (m *SearchManager) QueryByMetadata(ctx context.Context, body *schemas.MetadataQuery) (*schemas.MetadataQueryResults, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/metadata_queries"+"/execute_read")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.MetadataQueryResults)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchGetOptions carries the optional parameters.
type SearchGetOptions struct {
	Query                    *string
	Scope                    *schemas.GetScope
	FileExtensions           []string
	CreatedAtRange           []string
	UpdatedAtRange           []string
	SizeRange                []int64
	OwnerUserIds             []string
	RecentUpdaterUserIds     []string
	AncestorFolderIds        []string
	ContentTypes             []schemas.GetContentTypes
	Type                     *schemas.GetType
	TrashContent             *schemas.GetTrashContent
	Mdfilters                []schemas.MetadataFilter
	Sort                     *schemas.GetSort
	Direction                *schemas.GetDirection
	Limit                    *int64
	IncludeRecentSharedLinks *bool
	Fields                   []string
	Offset                   *int64
	DeletedUserIds           []string
	DeletedAtRange           []string
}

func (m *SearchManager) Get(ctx context.Context, opts *SearchGetOptions) (*schemas.SearchResultsResponse, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/search")
	if opts != nil {
		if opts.Query != nil {
			req = gantryruntime.WithQuery(req, "query", (*opts.Query))
		}
		if opts.Scope != nil {
			req = gantryruntime.WithQuery(req, "scope", string((*opts.Scope)))
		}
		if opts.FileExtensions != nil {
			req = gantryruntime.WithQuery(req, "file_extensions", strings.Join(opts.FileExtensions, ","))
		}
		if opts.CreatedAtRange != nil {
			req = gantryruntime.WithQuery(req, "created_at_range", strings.Join(opts.CreatedAtRange, ","))
		}
		if opts.UpdatedAtRange != nil {
			req = gantryruntime.WithQuery(req, "updated_at_range", strings.Join(opts.UpdatedAtRange, ","))
		}
		if opts.SizeRange != nil {
			req = gantryruntime.WithQuery(req, "size_range", joinInt64(opts.SizeRange))
		}
		if opts.OwnerUserIds != nil {
			req = gantryruntime.WithQuery(req, "owner_user_ids", strings.Join(opts.OwnerUserIds, ","))
		}
		if opts.RecentUpdaterUserIds != nil {
			req = gantryruntime.WithQuery(req, "recent_updater_user_ids", strings.Join(opts.RecentUpdaterUserIds, ","))
		}
		if opts.AncestorFolderIds != nil {
			req = gantryruntime.WithQuery(req, "ancestor_folder_ids", strings.Join(opts.AncestorFolderIds, ","))
		}
		if opts.ContentTypes != nil {
			req = gantryruntime.WithQuery(req, "content_types", joinStringLike(opts.ContentTypes))
		}
		if opts.Type != nil {
			req = gantryruntime.WithQuery(req, "type", string((*opts.Type)))
		}
		if opts.TrashContent != nil {
			req = gantryruntime.WithQuery(req, "trash_content", string((*opts.TrashContent)))
		}
		if opts.Mdfilters != nil {
			req = gantryruntime.WithQuery(req, "mdfilters", func() string { data, _ := json.Marshal(opts.Mdfilters); return string(data) }())
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", string((*opts.Sort)))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.IncludeRecentSharedLinks != nil {
			req = gantryruntime.WithQuery(req, "include_recent_shared_links", strconv.FormatBool((*opts.IncludeRecentSharedLinks)))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.DeletedUserIds != nil {
			req = gantryruntime.WithQuery(req, "deleted_user_ids", strings.Join(opts.DeletedUserIds, ","))
		}
		if opts.DeletedAtRange != nil {
			req = gantryruntime.WithQuery(req, "deleted_at_range", strings.Join(opts.DeletedAtRange, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SearchResultsResponse)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
