// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// SessionTerminationManager groups the "session_termination" operations.
type SessionTerminationManager struct {
	session *gantryruntime.Client
}

// NewSessionTerminationManager builds the manager against a runtime session.
func NewSessionTerminationManager(session *gantryruntime.Client) *SessionTerminationManager {
	return &SessionTerminationManager{session: session}
}

func (m *SessionTerminationManager) CreateUserTerminateSessions(ctx context.Context, body *schemas.UserTerminateSessionsCreateRequest) (*schemas.SessionTerminationMessage, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/users"+"/terminate_sessions")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SessionTerminationMessage)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SessionTerminationManager) CreateGroupTerminateSessions(ctx context.Context, body *schemas.GroupTerminateSessionsCreateRequest) (*schemas.SessionTerminationMessage, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/groups"+"/terminate_sessions")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SessionTerminationMessage)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
