// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
)

// SharedLinksAppItemsManager groups the "shared_links_app_items" operations.
type SharedLinksAppItemsManager struct {
	session *gantryruntime.Client
}

// NewSharedLinksAppItemsManager builds the manager against a runtime session.
func NewSharedLinksAppItemsManager(session *gantryruntime.Client) *SharedLinksAppItemsManager {
	return &SharedLinksAppItemsManager{session: session}
}

func (m *SharedLinksAppItemsManager) GetSharedItemsAppItems(ctx context.Context, boxapi string) (*schemas.AppItem, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shared_items")
	req = gantryruntime.WithHeader(req, "boxapi", boxapi)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.AppItem)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
