// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// SharedLinksFoldersManager groups the "shared_links_folders" operations.
type SharedLinksFoldersManager struct {
	session *gantryruntime.Client
}

// NewSharedLinksFoldersManager builds the manager against a runtime session.
func NewSharedLinksFoldersManager(session *gantryruntime.Client) *SharedLinksFoldersManager {
	return &SharedLinksFoldersManager{session: session}
}

// SharedLinksFoldersGetSharedItemsFoldersOptions carries the optional parameters.
type SharedLinksFoldersGetSharedItemsFoldersOptions struct {
	IfNoneMatch *string
	Fields      []string
}

func (m *SharedLinksFoldersManager) GetSharedItemsFolders(ctx context.Context, boxapi string, opts *SharedLinksFoldersGetSharedItemsFoldersOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shared_items")
	req = gantryruntime.WithHeader(req, "boxapi", boxapi)
	if opts != nil {
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFoldersManager) GetFolderGetSharedLink(ctx context.Context, folderId string, fields string) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFoldersManager) UpdateFolderAddSharedLink(ctx context.Context, folderId string, fields string, body *schemas.FileUpdateRequest2) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFoldersManager) UpdateFolderUpdateSharedLink(ctx context.Context, folderId string, fields string, body *schemas.FolderUpdateRequest2) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFoldersManager) UpdateFolderRemoveSharedLink(ctx context.Context, folderId string, fields string, body *schemas.FileUpdateRequest3) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
