// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// SharedLinksWebLinksManager groups the "shared_links_web_links" operations.
type SharedLinksWebLinksManager struct {
	session *gantryruntime.Client
}

// NewSharedLinksWebLinksManager builds the manager against a runtime session.
func NewSharedLinksWebLinksManager(session *gantryruntime.Client) *SharedLinksWebLinksManager {
	return &SharedLinksWebLinksManager{session: session}
}

// SharedLinksWebLinksGetSharedItemsWebLinksOptions carries the optional parameters.
type SharedLinksWebLinksGetSharedItemsWebLinksOptions struct {
	IfNoneMatch *string
	Fields      []string
}

func (m *SharedLinksWebLinksManager) GetSharedItemsWebLinks(ctx context.Context, boxapi string, opts *SharedLinksWebLinksGetSharedItemsWebLinksOptions) (*schemas.WebLink, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shared_items")
	req = gantryruntime.WithHeader(req, "boxapi", boxapi)
	if opts != nil {
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksWebLinksManager) GetWebLinkGetSharedLink(ctx context.Context, webLinkId string, fields string) (*schemas.WebLink, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksWebLinksManager) UpdateWebLinkAddSharedLink(ctx context.Context, webLinkId string, fields string, body *schemas.FileUpdateRequest2) (*schemas.WebLink, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksWebLinksManager) UpdateWebLinkUpdateSharedLink(ctx context.Context, webLinkId string, fields string, body *schemas.FileUpdateRequest2) (*schemas.WebLink, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksWebLinksManager) UpdateWebLinkRemoveSharedLink(ctx context.Context, webLinkId string, fields string, body *schemas.FileUpdateRequest3) (*schemas.WebLink, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
