// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// SharedLinksFilesManager groups the "shared_links_files" operations.
type SharedLinksFilesManager struct {
	session *gantryruntime.Client
}

// NewSharedLinksFilesManager builds the manager against a runtime session.
func NewSharedLinksFilesManager(session *gantryruntime.Client) *SharedLinksFilesManager {
	return &SharedLinksFilesManager{session: session}
}

// SharedLinksFilesGetSharedItemsOptions carries the optional parameters.
type SharedLinksFilesGetSharedItemsOptions struct {
	IfNoneMatch *string
	Fields      []string
}

func (m *SharedLinksFilesManager) GetSharedItems(ctx context.Context, boxapi string, opts *SharedLinksFilesGetSharedItemsOptions) (*schemas.FileFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shared_items")
	req = gantryruntime.WithHeader(req, "boxapi", boxapi)
	if opts != nil {
		if opts.IfNoneMatch != nil {
			req = gantryruntime.WithHeader(req, "if-none-match", (*opts.IfNoneMatch))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFilesManager) GetFileGetSharedLink(ctx context.Context, fileId string, fields string) (*schemas.FileFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFilesManager) UpdateFileAddSharedLink(ctx context.Context, fileId string, fields string, body *schemas.FileUpdateRequest2) (*schemas.FileFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFilesManager) UpdateFileUpdateSharedLink(ctx context.Context, fileId string, fields string, body *schemas.FileUpdateRequest2) (*schemas.FileFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SharedLinksFilesManager) UpdateFileRemoveSharedLink(ctx context.Context, fileId string, fields string, body *schemas.FileUpdateRequest3) (*schemas.FileFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	req = gantryruntime.WithQuery(req, "fields", fields)
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FileFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
