// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ShieldInformationBarrierSegmentMembersManager groups the "shield_information_barrier_segment_members" operations.
type ShieldInformationBarrierSegmentMembersManager struct {
	session *gantryruntime.Client
}

// NewShieldInformationBarrierSegmentMembersManager builds the manager against a runtime session.
func NewShieldInformationBarrierSegmentMembersManager(session *gantryruntime.Client) *ShieldInformationBarrierSegmentMembersManager {
	return &ShieldInformationBarrierSegmentMembersManager{session: session}
}

func (m *ShieldInformationBarrierSegmentMembersManager) Get(ctx context.Context, shieldInformationBarrierSegmentMemberId string) (*schemas.ShieldInformationBarrierSegmentMember, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segment_members"+"/"+url.PathEscape(shieldInformationBarrierSegmentMemberId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentMember)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentMembersManager) Delete(ctx context.Context, shieldInformationBarrierSegmentMemberId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/shield_information_barrier_segment_members"+"/"+url.PathEscape(shieldInformationBarrierSegmentMemberId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// ShieldInformationBarrierSegmentMembersListOptions carries the optional parameters.
type ShieldInformationBarrierSegmentMembersListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *ShieldInformationBarrierSegmentMembersManager) listPage(ctx context.Context, shieldInformationBarrierSegmentId string, opts *ShieldInformationBarrierSegmentMembersListOptions) (*schemas.ShieldInformationBarrierSegmentMembers, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segment_members")
	req = gantryruntime.WithQuery(req, "shield_information_barrier_segment_id", shieldInformationBarrierSegmentId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentMembers)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentMembersManager) List(ctx context.Context, shieldInformationBarrierSegmentId string, opts *ShieldInformationBarrierSegmentMembersListOptions) iter.Seq2[*schemas.ShieldInformationBarrierSegmentMember, error] {
	return func(yield func(*schemas.ShieldInformationBarrierSegmentMember, error) bool) {
		var o ShieldInformationBarrierSegmentMembersListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, shieldInformationBarrierSegmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ShieldInformationBarrierSegmentMembersManager) Create(ctx context.Context, body *schemas.ShieldInformationBarrierSegmentMemberCreateRequest) (*schemas.ShieldInformationBarrierSegmentMember, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barrier_segment_members")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentMember)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
