// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// ShieldListsManager groups the "shield_lists" operations.
type ShieldListsManager struct {
	session *gantryruntime.Client
}

// NewShieldListsManager builds the manager against a runtime session.
func NewShieldListsManager(session *gantryruntime.Client) *ShieldListsManager {
	return &ShieldListsManager{session: session}
}

func (m *ShieldListsManager) List(ctx context.Context) (*schemas.ShieldLists, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_lists")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldLists)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldListsManager) Create(ctx context.Context, body *schemas.ShieldListsCreate) (*schemas.ShieldList, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_lists")
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldList)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldListsManager) Get(ctx context.Context, shieldListId string) (*schemas.ShieldList, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_lists"+"/"+url.PathEscape(shieldListId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldList)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldListsManager) Update(ctx context.Context, shieldListId string, body *schemas.ShieldListsUpdate) (*schemas.ShieldList, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/shield_lists"+"/"+url.PathEscape(shieldListId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldList)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldListsManager) Delete(ctx context.Context, shieldListId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/shield_lists"+"/"+url.PathEscape(shieldListId))
	req = gantryruntime.WithHeader(req, "box-version", "2025.0")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
