// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ShieldInformationBarrierSegmentsManager groups the "shield_information_barrier_segments" operations.
type ShieldInformationBarrierSegmentsManager struct {
	session *gantryruntime.Client
}

// NewShieldInformationBarrierSegmentsManager builds the manager against a runtime session.
func NewShieldInformationBarrierSegmentsManager(session *gantryruntime.Client) *ShieldInformationBarrierSegmentsManager {
	return &ShieldInformationBarrierSegmentsManager{session: session}
}

func (m *ShieldInformationBarrierSegmentsManager) Get(ctx context.Context, shieldInformationBarrierSegmentId string) (*schemas.ShieldInformationBarrierSegment, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segments"+"/"+url.PathEscape(shieldInformationBarrierSegmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentsManager) Update(ctx context.Context, shieldInformationBarrierSegmentId string, body *schemas.ShieldInformationBarrierSegmentUpdateRequest) (*schemas.ShieldInformationBarrierSegment, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/shield_information_barrier_segments"+"/"+url.PathEscape(shieldInformationBarrierSegmentId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentsManager) Delete(ctx context.Context, shieldInformationBarrierSegmentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/shield_information_barrier_segments"+"/"+url.PathEscape(shieldInformationBarrierSegmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// ShieldInformationBarrierSegmentsListOptions carries the optional parameters.
type ShieldInformationBarrierSegmentsListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *ShieldInformationBarrierSegmentsManager) listPage(ctx context.Context, shieldInformationBarrierId string, opts *ShieldInformationBarrierSegmentsListOptions) (*schemas.ShieldInformationBarrierSegments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segments")
	req = gantryruntime.WithQuery(req, "shield_information_barrier_id", shieldInformationBarrierId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentsManager) List(ctx context.Context, shieldInformationBarrierId string, opts *ShieldInformationBarrierSegmentsListOptions) iter.Seq2[*schemas.ShieldInformationBarrierSegment, error] {
	return func(yield func(*schemas.ShieldInformationBarrierSegment, error) bool) {
		var o ShieldInformationBarrierSegmentsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, shieldInformationBarrierId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ShieldInformationBarrierSegmentsManager) Create(ctx context.Context, body *schemas.ShieldInformationBarrierSegmentCreateRequest) (*schemas.ShieldInformationBarrierSegment, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barrier_segments")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
