// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ShieldInformationBarrierReportsManager groups the "shield_information_barrier_reports" operations.
type ShieldInformationBarrierReportsManager struct {
	session *gantryruntime.Client
}

// NewShieldInformationBarrierReportsManager builds the manager against a runtime session.
func NewShieldInformationBarrierReportsManager(session *gantryruntime.Client) *ShieldInformationBarrierReportsManager {
	return &ShieldInformationBarrierReportsManager{session: session}
}

// ShieldInformationBarrierReportsListOptions carries the optional parameters.
type ShieldInformationBarrierReportsListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *ShieldInformationBarrierReportsManager) listPage(ctx context.Context, shieldInformationBarrierId string, opts *ShieldInformationBarrierReportsListOptions) (*schemas.ShieldInformationBarrierReports, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_reports")
	req = gantryruntime.WithQuery(req, "shield_information_barrier_id", shieldInformationBarrierId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierReports)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierReportsManager) List(ctx context.Context, shieldInformationBarrierId string, opts *ShieldInformationBarrierReportsListOptions) iter.Seq2[*schemas.ShieldInformationBarrierReport, error] {
	return func(yield func(*schemas.ShieldInformationBarrierReport, error) bool) {
		var o ShieldInformationBarrierReportsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, shieldInformationBarrierId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ShieldInformationBarrierReportsManager) Create(ctx context.Context, body *schemas.ShieldInformationBarrierReference) (*schemas.ShieldInformationBarrierReport, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barrier_reports")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierReport)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierReportsManager) Get(ctx context.Context, shieldInformationBarrierReportId string) (*schemas.ShieldInformationBarrierReport, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_reports"+"/"+url.PathEscape(shieldInformationBarrierReportId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierReport)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
