// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ShieldInformationBarriersManager groups the "shield_information_barriers" operations.
type ShieldInformationBarriersManager struct {
	session *gantryruntime.Client
}

// NewShieldInformationBarriersManager builds the manager against a runtime session.
func NewShieldInformationBarriersManager(session *gantryruntime.Client) *ShieldInformationBarriersManager {
	return &ShieldInformationBarriersManager{session: session}
}

func (m *ShieldInformationBarriersManager) Get(ctx context.Context, shieldInformationBarrierId string) (*schemas.ShieldInformationBarrier, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barriers"+"/"+url.PathEscape(shieldInformationBarrierId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrier)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarriersManager) CreateChangeStatus(ctx context.Context, body *schemas.ChangeStatusCreateRequest) (*schemas.ShieldInformationBarrier, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barriers"+"/change_status")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrier)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// ShieldInformationBarriersListOptions carries the optional parameters.
type ShieldInformationBarriersListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *ShieldInformationBarriersManager) listPage(ctx context.Context, opts *ShieldInformationBarriersListOptions) (*schemas.ShieldInformationBarriers, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barriers")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarriers)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarriersManager) List(ctx context.Context, opts *ShieldInformationBarriersListOptions) iter.Seq2[*schemas.ShieldInformationBarrier, error] {
	return func(yield func(*schemas.ShieldInformationBarrier, error) bool) {
		var o ShieldInformationBarriersListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ShieldInformationBarriersManager) Create(ctx context.Context, body *schemas.ShieldInformationBarrierCreateRequest) (*schemas.ShieldInformationBarrier, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barriers")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrier)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
