// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// ShieldInformationBarrierSegmentRestrictionsManager groups the "shield_information_barrier_segment_restrictions" operations.
type ShieldInformationBarrierSegmentRestrictionsManager struct {
	session *gantryruntime.Client
}

// NewShieldInformationBarrierSegmentRestrictionsManager builds the manager against a runtime session.
func NewShieldInformationBarrierSegmentRestrictionsManager(session *gantryruntime.Client) *ShieldInformationBarrierSegmentRestrictionsManager {
	return &ShieldInformationBarrierSegmentRestrictionsManager{session: session}
}

func (m *ShieldInformationBarrierSegmentRestrictionsManager) Get(ctx context.Context, shieldInformationBarrierSegmentRestrictionId string) (*schemas.ShieldInformationBarrierSegmentRestriction, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segment_restrictions"+"/"+url.PathEscape(shieldInformationBarrierSegmentRestrictionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentRestriction)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentRestrictionsManager) Delete(ctx context.Context, shieldInformationBarrierSegmentRestrictionId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/shield_information_barrier_segment_restrictions"+"/"+url.PathEscape(shieldInformationBarrierSegmentRestrictionId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// ShieldInformationBarrierSegmentRestrictionsListOptions carries the optional parameters.
type ShieldInformationBarrierSegmentRestrictionsListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *ShieldInformationBarrierSegmentRestrictionsManager) listPage(ctx context.Context, shieldInformationBarrierSegmentId string, opts *ShieldInformationBarrierSegmentRestrictionsListOptions) (*schemas.ShieldInformationBarrierSegmentRestrictions, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/shield_information_barrier_segment_restrictions")
	req = gantryruntime.WithQuery(req, "shield_information_barrier_segment_id", shieldInformationBarrierSegmentId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentRestrictions)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ShieldInformationBarrierSegmentRestrictionsManager) List(ctx context.Context, shieldInformationBarrierSegmentId string, opts *ShieldInformationBarrierSegmentRestrictionsListOptions) iter.Seq2[*schemas.ShieldInformationBarrierSegmentRestriction, error] {
	return func(yield func(*schemas.ShieldInformationBarrierSegmentRestriction, error) bool) {
		var o ShieldInformationBarrierSegmentRestrictionsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, shieldInformationBarrierSegmentId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *ShieldInformationBarrierSegmentRestrictionsManager) Create(ctx context.Context, body *schemas.ShieldInformationBarrierSegmentRestrictionCreateRequest) (*schemas.ShieldInformationBarrierSegmentRestriction, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/shield_information_barrier_segment_restrictions")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ShieldInformationBarrierSegmentRestriction)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
