// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// SignTemplatesManager groups the "sign_templates" operations.
type SignTemplatesManager struct {
	session *gantryruntime.Client
}

// NewSignTemplatesManager builds the manager against a runtime session.
func NewSignTemplatesManager(session *gantryruntime.Client) *SignTemplatesManager {
	return &SignTemplatesManager{session: session}
}

// SignTemplatesListOptions carries the optional parameters.
type SignTemplatesListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *SignTemplatesManager) listPage(ctx context.Context, opts *SignTemplatesListOptions) (*schemas.SignTemplates, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/sign_templates")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignTemplates)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SignTemplatesManager) List(ctx context.Context, opts *SignTemplatesListOptions) iter.Seq2[*schemas.SignTemplate, error] {
	return func(yield func(*schemas.SignTemplate, error) bool) {
		var o SignTemplatesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *SignTemplatesManager) Get(ctx context.Context, templateId string) (*schemas.SignTemplate, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/sign_templates"+"/"+url.PathEscape(templateId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignTemplate)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
