// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// SignRequestsManager groups the "sign_requests" operations.
type SignRequestsManager struct {
	session *gantryruntime.Client
}

// NewSignRequestsManager builds the manager against a runtime session.
func NewSignRequestsManager(session *gantryruntime.Client) *SignRequestsManager {
	return &SignRequestsManager{session: session}
}

func (m *SignRequestsManager) Cancel(ctx context.Context, signRequestId string, body *schemas.SignRequestCancelRequest) (*schemas.SignRequest, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/sign_requests"+"/"+url.PathEscape(signRequestId)+"/cancel")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SignRequestsManager) Resend(ctx context.Context, signRequestId string) error {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/sign_requests"+"/"+url.PathEscape(signRequestId)+"/resend")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *SignRequestsManager) Get(ctx context.Context, signRequestId string) (*schemas.SignRequest, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/sign_requests"+"/"+url.PathEscape(signRequestId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// SignRequestsListOptions carries the optional parameters.
type SignRequestsListOptions struct {
	Marker         *string
	Limit          *int64
	Senders        []string
	SharedRequests *bool
}

func (m *SignRequestsManager) listPage(ctx context.Context, opts *SignRequestsListOptions) (*schemas.SignRequests, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/sign_requests")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Senders != nil {
			req = gantryruntime.WithQuery(req, "senders", strings.Join(opts.Senders, ","))
		}
		if opts.SharedRequests != nil {
			req = gantryruntime.WithQuery(req, "shared_requests", strconv.FormatBool((*opts.SharedRequests)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignRequests)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SignRequestsManager) List(ctx context.Context, opts *SignRequestsListOptions) iter.Seq2[*schemas.SignRequest, error] {
	return func(yield func(*schemas.SignRequest, error) bool) {
		var o SignRequestsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *SignRequestsManager) Create(ctx context.Context, body *schemas.SignRequestCreateRequest) (*schemas.SignRequest, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/sign_requests")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SignRequest)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
