// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// SkillsManager groups the "skills" operations.
type SkillsManager struct {
	session *gantryruntime.Client
}

// NewSkillsManager builds the manager against a runtime session.
func NewSkillsManager(session *gantryruntime.Client) *SkillsManager {
	return &SkillsManager{session: session}
}

func (m *SkillsManager) Get(ctx context.Context, fileId string) (*schemas.SkillCardsMetadata, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/global"+"/boxSkillsCards")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SkillCardsMetadata)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SkillsManager) Update(ctx context.Context, fileId string, body []schemas.SkillUpdateRequest) (*schemas.SkillCardsMetadata, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/global"+"/boxSkillsCards")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SkillCardsMetadata)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SkillsManager) Create(ctx context.Context, fileId string, body *schemas.SkillCreateRequest) (*schemas.SkillCardsMetadata, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/global"+"/boxSkillsCards")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.SkillCardsMetadata)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *SkillsManager) Delete(ctx context.Context, fileId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/metadata"+"/global"+"/boxSkillsCards")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

func (m *SkillsManager) UpdateSkillInvocation(ctx context.Context, skillId string, body *schemas.SkillInvocationUpdateRequest) error {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/skill_invocations"+"/"+url.PathEscape(skillId))
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
