// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// StoragePoliciesManager groups the "storage_policies" operations.
type StoragePoliciesManager struct {
	session *gantryruntime.Client
}

// NewStoragePoliciesManager builds the manager against a runtime session.
func NewStoragePoliciesManager(session *gantryruntime.Client) *StoragePoliciesManager {
	return &StoragePoliciesManager{session: session}
}

// StoragePoliciesListOptions carries the optional parameters.
type StoragePoliciesListOptions struct {
	Fields []string
	Marker *string
	Limit  *int64
}

func (m *StoragePoliciesManager) listPage(ctx context.Context, opts *StoragePoliciesListOptions) (*schemas.StoragePolicies, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/storage_policies")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicies)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *StoragePoliciesManager) List(ctx context.Context, opts *StoragePoliciesListOptions) iter.Seq2[*schemas.StoragePolicy, error] {
	return func(yield func(*schemas.StoragePolicy, error) bool) {
		var o StoragePoliciesListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *StoragePoliciesManager) Get(ctx context.Context, storagePolicyId string) (*schemas.StoragePolicy, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/storage_policies"+"/"+url.PathEscape(storagePolicyId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicy)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
