// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
)

// StoragePolicyAssignmentsManager groups the "storage_policy_assignments" operations.
type StoragePolicyAssignmentsManager struct {
	session *gantryruntime.Client
}

// NewStoragePolicyAssignmentsManager builds the manager against a runtime session.
func NewStoragePolicyAssignmentsManager(session *gantryruntime.Client) *StoragePolicyAssignmentsManager {
	return &StoragePolicyAssignmentsManager{session: session}
}

// StoragePolicyAssignmentsListOptions carries the optional parameters.
type StoragePolicyAssignmentsListOptions struct {
	Marker *string
}

func (m *StoragePolicyAssignmentsManager) listPage(ctx context.Context, resolvedForType schemas.GetResolvedForType, resolvedForId string, opts *StoragePolicyAssignmentsListOptions) (*schemas.StoragePolicyAssignments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/storage_policy_assignments")
	req = gantryruntime.WithQuery(req, "resolved_for_type", string(resolvedForType))
	req = gantryruntime.WithQuery(req, "resolved_for_id", resolvedForId)
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicyAssignments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *StoragePolicyAssignmentsManager) List(ctx context.Context, resolvedForType schemas.GetResolvedForType, resolvedForId string, opts *StoragePolicyAssignmentsListOptions) iter.Seq2[*schemas.StoragePolicyAssignment, error] {
	return func(yield func(*schemas.StoragePolicyAssignment, error) bool) {
		var o StoragePolicyAssignmentsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, resolvedForType, resolvedForId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *StoragePolicyAssignmentsManager) Create(ctx context.Context, body *schemas.StoragePolicyAssignmentCreateRequest) (*schemas.StoragePolicyAssignment, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/storage_policy_assignments")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *StoragePolicyAssignmentsManager) Get(ctx context.Context, storagePolicyAssignmentId string) (*schemas.StoragePolicyAssignment, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/storage_policy_assignments"+"/"+url.PathEscape(storagePolicyAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *StoragePolicyAssignmentsManager) Update(ctx context.Context, storagePolicyAssignmentId string, body *schemas.StoragePolicyAssignmentUpdateRequest) (*schemas.StoragePolicyAssignment, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/storage_policy_assignments"+"/"+url.PathEscape(storagePolicyAssignmentId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.StoragePolicyAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *StoragePolicyAssignmentsManager) Delete(ctx context.Context, storagePolicyAssignmentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/storage_policy_assignments"+"/"+url.PathEscape(storagePolicyAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
