// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// TasksManager groups the "tasks" operations.
type TasksManager struct {
	session *gantryruntime.Client
}

// NewTasksManager builds the manager against a runtime session.
func NewTasksManager(session *gantryruntime.Client) *TasksManager {
	return &TasksManager{session: session}
}

func (m *TasksManager) ListFile(ctx context.Context, fileId string) (*schemas.Tasks, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/tasks")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Tasks)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TasksManager) Create(ctx context.Context, body *schemas.TaskCreateRequest) (*schemas.Task, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/tasks")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Task)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TasksManager) Get(ctx context.Context, taskId string) (*schemas.Task, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/tasks"+"/"+url.PathEscape(taskId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Task)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TasksManager) Update(ctx context.Context, taskId string, body *schemas.TaskUpdateRequest) (*schemas.Task, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/tasks"+"/"+url.PathEscape(taskId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Task)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TasksManager) Delete(ctx context.Context, taskId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/tasks"+"/"+url.PathEscape(taskId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
