// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// TaskAssignmentsManager groups the "task_assignments" operations.
type TaskAssignmentsManager struct {
	session *gantryruntime.Client
}

// NewTaskAssignmentsManager builds the manager against a runtime session.
func NewTaskAssignmentsManager(session *gantryruntime.Client) *TaskAssignmentsManager {
	return &TaskAssignmentsManager{session: session}
}

func (m *TaskAssignmentsManager) ListTaskAssignments(ctx context.Context, taskId string) (*schemas.TaskAssignments, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/tasks"+"/"+url.PathEscape(taskId)+"/assignments")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TaskAssignments)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TaskAssignmentsManager) Create(ctx context.Context, body *schemas.TaskAssignmentCreateRequest) (*schemas.TaskAssignment, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/task_assignments")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TaskAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TaskAssignmentsManager) Get(ctx context.Context, taskAssignmentId string) (*schemas.TaskAssignment, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/task_assignments"+"/"+url.PathEscape(taskAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TaskAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TaskAssignmentsManager) Update(ctx context.Context, taskAssignmentId string, body *schemas.TaskAssignmentUpdateRequest) (*schemas.TaskAssignment, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/task_assignments"+"/"+url.PathEscape(taskAssignmentId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TaskAssignment)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TaskAssignmentsManager) Delete(ctx context.Context, taskAssignmentId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/task_assignments"+"/"+url.PathEscape(taskAssignmentId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
