// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// TermsOfServiceUserStatusesManager groups the "terms_of_service_user_statuses" operations.
type TermsOfServiceUserStatusesManager struct {
	session *gantryruntime.Client
}

// NewTermsOfServiceUserStatusesManager builds the manager against a runtime session.
func NewTermsOfServiceUserStatusesManager(session *gantryruntime.Client) *TermsOfServiceUserStatusesManager {
	return &TermsOfServiceUserStatusesManager{session: session}
}

// TermsOfServiceUserStatusesListOptions carries the optional parameters.
type TermsOfServiceUserStatusesListOptions struct {
	UserId *string
}

func (m *TermsOfServiceUserStatusesManager) List(ctx context.Context, tosId string, opts *TermsOfServiceUserStatusesListOptions) (*schemas.TermsOfServiceUserStatuses, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/terms_of_service_user_statuses")
	req = gantryruntime.WithQuery(req, "tos_id", tosId)
	if opts != nil {
		if opts.UserId != nil {
			req = gantryruntime.WithQuery(req, "user_id", (*opts.UserId))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfServiceUserStatuses)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TermsOfServiceUserStatusesManager) Create(ctx context.Context, body *schemas.TermsOfServiceUserStatuseCreateRequest) (*schemas.TermsOfServiceUserStatus, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/terms_of_service_user_statuses")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfServiceUserStatus)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TermsOfServiceUserStatusesManager) Update(ctx context.Context, termsOfServiceUserStatusId string, body *schemas.TermsOfServiceUserStatuseUpdateRequest) (*schemas.TermsOfServiceUserStatus, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/terms_of_service_user_statuses"+"/"+url.PathEscape(termsOfServiceUserStatusId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfServiceUserStatus)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
