// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// TermsOfServicesManager groups the "terms_of_services" operations.
type TermsOfServicesManager struct {
	session *gantryruntime.Client
}

// NewTermsOfServicesManager builds the manager against a runtime session.
func NewTermsOfServicesManager(session *gantryruntime.Client) *TermsOfServicesManager {
	return &TermsOfServicesManager{session: session}
}

// TermsOfServicesListOptions carries the optional parameters.
type TermsOfServicesListOptions struct {
	TosType *schemas.GetTosType
}

func (m *TermsOfServicesManager) List(ctx context.Context, opts *TermsOfServicesListOptions) (*schemas.TermsOfServices, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/terms_of_services")
	if opts != nil {
		if opts.TosType != nil {
			req = gantryruntime.WithQuery(req, "tos_type", string((*opts.TosType)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfServices)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TermsOfServicesManager) Create(ctx context.Context, body *schemas.TermsOfServiceCreateRequest) (*schemas.TermsOfService, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/terms_of_services")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfService)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TermsOfServicesManager) Get(ctx context.Context, termsOfServiceId string) (*schemas.TermsOfService, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/terms_of_services"+"/"+url.PathEscape(termsOfServiceId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfService)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TermsOfServicesManager) Update(ctx context.Context, termsOfServiceId string, body *schemas.TermsOfServiceUpdateRequest) (*schemas.TermsOfService, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/terms_of_services"+"/"+url.PathEscape(termsOfServiceId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TermsOfService)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
