// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strconv"
	"strings"
)

// TransferManager groups the "transfer" operations.
type TransferManager struct {
	session *gantryruntime.Client
}

// NewTransferManager builds the manager against a runtime session.
func NewTransferManager(session *gantryruntime.Client) *TransferManager {
	return &TransferManager{session: session}
}

// TransferTransferFoldersOptions carries the optional parameters.
type TransferTransferFoldersOptions struct {
	Fields []string
	Notify *bool
}

func (m *TransferManager) TransferFolders(ctx context.Context, userId string, body *schemas.UserFolder0UpdateRequest, opts *TransferTransferFoldersOptions) (*schemas.FolderFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId)+"/folders"+"/0")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Notify != nil {
			req = gantryruntime.WithQuery(req, "notify", strconv.FormatBool((*opts.Notify)))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.FolderFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
