// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// TrashedWebLinksManager groups the "trashed_web_links" operations.
type TrashedWebLinksManager struct {
	session *gantryruntime.Client
}

// NewTrashedWebLinksManager builds the manager against a runtime session.
func NewTrashedWebLinksManager(session *gantryruntime.Client) *TrashedWebLinksManager {
	return &TrashedWebLinksManager{session: session}
}

// TrashedWebLinksCreateWebLinkOptions carries the optional parameters.
type TrashedWebLinksCreateWebLinkOptions struct {
	Fields []string
}

func (m *TrashedWebLinksManager) CreateWebLink(ctx context.Context, webLinkId string, body *schemas.FileCreateRequest, opts *TrashedWebLinksCreateWebLinkOptions) (*schemas.TrashWebLinkRestored, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashWebLinkRestored)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// TrashedWebLinksGetWebLinkTrashOptions carries the optional parameters.
type TrashedWebLinksGetWebLinkTrashOptions struct {
	Fields []string
}

func (m *TrashedWebLinksManager) GetWebLinkTrash(ctx context.Context, webLinkId string, opts *TrashedWebLinksGetWebLinkTrashOptions) (*schemas.TrashWebLink, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId)+"/trash")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashWebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TrashedWebLinksManager) DeleteWebLinkTrash(ctx context.Context, webLinkId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId)+"/trash")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
