// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"strconv"
	"strings"
)

// TrashedItemsManager groups the "trashed_items" operations.
type TrashedItemsManager struct {
	session *gantryruntime.Client
}

// NewTrashedItemsManager builds the manager against a runtime session.
func NewTrashedItemsManager(session *gantryruntime.Client) *TrashedItemsManager {
	return &TrashedItemsManager{session: session}
}

// TrashedItemsListFolderTrashItemsOptions carries the optional parameters.
type TrashedItemsListFolderTrashItemsOptions struct {
	Fields    []string
	Limit     *int64
	Offset    *int64
	Usemarker *bool
	Marker    *string
	Direction *schemas.OrderDirection
	Sort      *schemas.GetFolderTrashItemsSort
}

func (m *TrashedItemsManager) listFolderTrashItemsPage(ctx context.Context, opts *TrashedItemsListFolderTrashItemsOptions) (*schemas.Items, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/trash"+"/items")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Usemarker != nil {
			req = gantryruntime.WithQuery(req, "usemarker", strconv.FormatBool((*opts.Usemarker)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Direction != nil {
			req = gantryruntime.WithQuery(req, "direction", string((*opts.Direction)))
		}
		if opts.Sort != nil {
			req = gantryruntime.WithQuery(req, "sort", string((*opts.Sort)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Items)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TrashedItemsManager) ListFolderTrashItems(ctx context.Context, opts *TrashedItemsListFolderTrashItemsOptions) iter.Seq2[*schemas.Item, error] {
	return func(yield func(*schemas.Item, error) bool) {
		var o TrashedItemsListFolderTrashItemsOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listFolderTrashItemsPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}
