// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// TrashedFilesManager groups the "trashed_files" operations.
type TrashedFilesManager struct {
	session *gantryruntime.Client
}

// NewTrashedFilesManager builds the manager against a runtime session.
func NewTrashedFilesManager(session *gantryruntime.Client) *TrashedFilesManager {
	return &TrashedFilesManager{session: session}
}

// TrashedFilesCreateFileOptions carries the optional parameters.
type TrashedFilesCreateFileOptions struct {
	Fields []string
}

func (m *TrashedFilesManager) CreateFile(ctx context.Context, fileId string, body *schemas.FileCreateRequest, opts *TrashedFilesCreateFileOptions) (*schemas.TrashFileRestored, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashFileRestored)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// TrashedFilesGetFileTrashOptions carries the optional parameters.
type TrashedFilesGetFileTrashOptions struct {
	Fields []string
}

func (m *TrashedFilesManager) GetFileTrash(ctx context.Context, fileId string, opts *TrashedFilesGetFileTrashOptions) (*schemas.TrashFile, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/trash")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashFile)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TrashedFilesManager) DeleteFileTrash(ctx context.Context, fileId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/files"+"/"+url.PathEscape(fileId)+"/trash")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
