// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// TrashedFoldersManager groups the "trashed_folders" operations.
type TrashedFoldersManager struct {
	session *gantryruntime.Client
}

// NewTrashedFoldersManager builds the manager against a runtime session.
func NewTrashedFoldersManager(session *gantryruntime.Client) *TrashedFoldersManager {
	return &TrashedFoldersManager{session: session}
}

// TrashedFoldersCreateFolderOptions carries the optional parameters.
type TrashedFoldersCreateFolderOptions struct {
	Fields []string
}

func (m *TrashedFoldersManager) CreateFolder(ctx context.Context, folderId string, body *schemas.FileCreateRequest, opts *TrashedFoldersCreateFolderOptions) (*schemas.TrashFolderRestored, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashFolderRestored)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// TrashedFoldersGetFolderTrashOptions carries the optional parameters.
type TrashedFoldersGetFolderTrashOptions struct {
	Fields []string
}

func (m *TrashedFoldersManager) GetFolderTrash(ctx context.Context, folderId string, opts *TrashedFoldersGetFolderTrashOptions) (*schemas.TrashFolder, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/trash")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.TrashFolder)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *TrashedFoldersManager) DeleteFolderTrash(ctx context.Context, folderId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/folders"+"/"+url.PathEscape(folderId)+"/trash")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
