// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strings"
)

// UploadsManager groups the "uploads" operations.
type UploadsManager struct {
	session *gantryruntime.Client
}

// NewUploadsManager builds the manager against a runtime session.
func NewUploadsManager(session *gantryruntime.Client) *UploadsManager {
	return &UploadsManager{session: session}
}

// UploadsCreateFileContentOptions carries the optional parameters.
type UploadsCreateFileContentOptions struct {
	IfMatch    *string
	Fields     []string
	ContentMd5 *string
}

func (m *UploadsManager) CreateFileContent(ctx context.Context, fileId string, body *schemas.FileIdContentCreateRequest, opts *UploadsCreateFileContentOptions) (*schemas.Files, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("upload")+"/files"+"/"+url.PathEscape(fileId)+"/content")
	if opts != nil {
		if opts.IfMatch != nil {
			req = gantryruntime.WithHeader(req, "if-match", (*opts.IfMatch))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.ContentMd5 != nil {
			req = gantryruntime.WithHeader(req, "content-md5", (*opts.ContentMd5))
		}
	}
	attributes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithMultipartBody(req, attributes, "file", nil)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Files)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// UploadsCreateFileContent2Options carries the optional parameters.
type UploadsCreateFileContent2Options struct {
	Fields     []string
	ContentMd5 *string
}

func (m *UploadsManager) CreateFileContent2(ctx context.Context, body *schemas.FileContentCreateRequest, opts *UploadsCreateFileContent2Options) (*schemas.Files, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("upload")+"/files"+"/content")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.ContentMd5 != nil {
			req = gantryruntime.WithHeader(req, "content-md5", (*opts.ContentMd5))
		}
	}
	attributes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithMultipartBody(req, attributes, "file", nil)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Files)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *UploadsManager) OptionFileContent(ctx context.Context, body *schemas.OptionFileContentRequest) (*schemas.UploadUrl, error) {
	req := m.session.NewRequest("OPTIONS", m.session.BaseUrl("api")+"/files"+"/content")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UploadUrl)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
