// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
	"strconv"
	"strings"
)

// UserCollaborationsManager groups the "user_collaborations" operations.
type UserCollaborationsManager struct {
	session *gantryruntime.Client
}

// NewUserCollaborationsManager builds the manager against a runtime session.
func NewUserCollaborationsManager(session *gantryruntime.Client) *UserCollaborationsManager {
	return &UserCollaborationsManager{session: session}
}

// UserCollaborationsGetCollaborationOptions carries the optional parameters.
type UserCollaborationsGetCollaborationOptions struct {
	Fields []string
}

func (m *UserCollaborationsManager) GetCollaboration(ctx context.Context, collaborationId string, opts *UserCollaborationsGetCollaborationOptions) (*schemas.Collaboration, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/collaborations"+"/"+url.PathEscape(collaborationId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *UserCollaborationsManager) UpdateCollaboration(ctx context.Context, collaborationId string, body *schemas.CollaborationUpdateRequest) (*schemas.Collaboration, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/collaborations"+"/"+url.PathEscape(collaborationId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *UserCollaborationsManager) DeleteCollaboration(ctx context.Context, collaborationId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/collaborations"+"/"+url.PathEscape(collaborationId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}

// UserCollaborationsCreateCollaborationsOptions carries the optional parameters.
type UserCollaborationsCreateCollaborationsOptions struct {
	Fields []string
	Notify *bool
}

func (m *UserCollaborationsManager) CreateCollaborations(ctx context.Context, body *schemas.CollaborationsCreateRequest, opts *UserCollaborationsCreateCollaborationsOptions) (*schemas.Collaboration, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/collaborations")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Notify != nil {
			req = gantryruntime.WithQuery(req, "notify", strconv.FormatBool((*opts.Notify)))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Collaboration)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
