// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
	"strings"
)

// UsersManager groups the "users" operations.
type UsersManager struct {
	session *gantryruntime.Client
}

// NewUsersManager builds the manager against a runtime session.
func NewUsersManager(session *gantryruntime.Client) *UsersManager {
	return &UsersManager{session: session}
}

// UsersListOptions carries the optional parameters.
type UsersListOptions struct {
	FilterTerm        *string
	UserType          *schemas.GetUserType
	ExternalAppUserId *string
	Fields            []string
	Offset            *int64
	Limit             *int64
	Usemarker         *bool
	Marker            *string
}

func (m *UsersManager) listPage(ctx context.Context, opts *UsersListOptions) (*schemas.Users, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users")
	if opts != nil {
		if opts.FilterTerm != nil {
			req = gantryruntime.WithQuery(req, "filter_term", (*opts.FilterTerm))
		}
		if opts.UserType != nil {
			req = gantryruntime.WithQuery(req, "user_type", string((*opts.UserType)))
		}
		if opts.ExternalAppUserId != nil {
			req = gantryruntime.WithQuery(req, "external_app_user_id", (*opts.ExternalAppUserId))
		}
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
		if opts.Offset != nil {
			req = gantryruntime.WithQuery(req, "offset", strconv.FormatInt((*opts.Offset), 10))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Usemarker != nil {
			req = gantryruntime.WithQuery(req, "usemarker", strconv.FormatBool((*opts.Usemarker)))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Users)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *UsersManager) List(ctx context.Context, opts *UsersListOptions) iter.Seq2[*schemas.UserFull, error] {
	return func(yield func(*schemas.UserFull, error) bool) {
		var o UsersListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

// UsersCreateOptions carries the optional parameters.
type UsersCreateOptions struct {
	Fields []string
}

func (m *UsersManager) Create(ctx context.Context, body *schemas.UserCreateRequest, opts *UsersCreateOptions) (*schemas.UserFull, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/users")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UserFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// UsersGetMeOptions carries the optional parameters.
type UsersGetMeOptions struct {
	Fields []string
}

func (m *UsersManager) GetMe(ctx context.Context, opts *UsersGetMeOptions) (*schemas.UserFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users"+"/me")
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UserFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// UsersGetOptions carries the optional parameters.
type UsersGetOptions struct {
	Fields []string
}

func (m *UsersManager) Get(ctx context.Context, userId string, opts *UsersGetOptions) (*schemas.UserFull, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UserFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// UsersUpdateOptions carries the optional parameters.
type UsersUpdateOptions struct {
	Fields []string
}

func (m *UsersManager) Update(ctx context.Context, userId string, body *schemas.UserUpdateRequest, opts *UsersUpdateOptions) (*schemas.UserFull, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId))
	if opts != nil {
		if opts.Fields != nil {
			req = gantryruntime.WithQuery(req, "fields", strings.Join(opts.Fields, ","))
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.UserFull)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// UsersDeleteOptions carries the optional parameters.
type UsersDeleteOptions struct {
	Notify *bool
	Force  *bool
}

func (m *UsersManager) Delete(ctx context.Context, userId string, opts *UsersDeleteOptions) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/users"+"/"+url.PathEscape(userId))
	if opts != nil {
		if opts.Notify != nil {
			req = gantryruntime.WithQuery(req, "notify", strconv.FormatBool((*opts.Notify)))
		}
		if opts.Force != nil {
			req = gantryruntime.WithQuery(req, "force", strconv.FormatBool((*opts.Force)))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
