// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"net/url"
)

// WebLinksManager groups the "web_links" operations.
type WebLinksManager struct {
	session *gantryruntime.Client
}

// NewWebLinksManager builds the manager against a runtime session.
func NewWebLinksManager(session *gantryruntime.Client) *WebLinksManager {
	return &WebLinksManager{session: session}
}

func (m *WebLinksManager) Create(ctx context.Context, body *schemas.WebLinkCreateRequest) (*schemas.WebLink, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/web_links")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

// WebLinksGetOptions carries the optional parameters.
type WebLinksGetOptions struct {
	Boxapi *string
}

func (m *WebLinksManager) Get(ctx context.Context, webLinkId string, opts *WebLinksGetOptions) (*schemas.WebLink, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	if opts != nil {
		if opts.Boxapi != nil {
			req = gantryruntime.WithHeader(req, "boxapi", (*opts.Boxapi))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebLinksManager) Update(ctx context.Context, webLinkId string, body *schemas.WebLinkUpdateRequest) (*schemas.WebLink, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.WebLink)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebLinksManager) Delete(ctx context.Context, webLinkId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/web_links"+"/"+url.PathEscape(webLinkId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
