// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// WebhooksManager groups the "webhooks" operations.
type WebhooksManager struct {
	session *gantryruntime.Client
}

// NewWebhooksManager builds the manager against a runtime session.
func NewWebhooksManager(session *gantryruntime.Client) *WebhooksManager {
	return &WebhooksManager{session: session}
}

// WebhooksListOptions carries the optional parameters.
type WebhooksListOptions struct {
	Marker *string
	Limit  *int64
}

func (m *WebhooksManager) listPage(ctx context.Context, opts *WebhooksListOptions) (*schemas.Webhooks, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/webhooks")
	if opts != nil {
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Webhooks)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebhooksManager) List(ctx context.Context, opts *WebhooksListOptions) iter.Seq2[*schemas.WebhookMini, error] {
	return func(yield func(*schemas.WebhookMini, error) bool) {
		var o WebhooksListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *WebhooksManager) Create(ctx context.Context, body *schemas.WebhookCreateRequest) (*schemas.Webhook, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/webhooks")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Webhook)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebhooksManager) Get(ctx context.Context, webhookId string) (*schemas.Webhook, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/webhooks"+"/"+url.PathEscape(webhookId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Webhook)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebhooksManager) Update(ctx context.Context, webhookId string, body *schemas.WebhookUpdateRequest) (*schemas.Webhook, error) {
	req := m.session.NewRequest("PUT", m.session.BaseUrl("api")+"/webhooks"+"/"+url.PathEscape(webhookId))
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Webhook)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WebhooksManager) Delete(ctx context.Context, webhookId string) error {
	req := m.session.NewRequest("DELETE", m.session.BaseUrl("api")+"/webhooks"+"/"+url.PathEscape(webhookId))
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
