// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"iter"
	"net/url"
	"strconv"
)

// WorkflowsManager groups the "workflows" operations.
type WorkflowsManager struct {
	session *gantryruntime.Client
}

// NewWorkflowsManager builds the manager against a runtime session.
func NewWorkflowsManager(session *gantryruntime.Client) *WorkflowsManager {
	return &WorkflowsManager{session: session}
}

// WorkflowsListOptions carries the optional parameters.
type WorkflowsListOptions struct {
	TriggerType *string
	Limit       *int64
	Marker      *string
}

func (m *WorkflowsManager) listPage(ctx context.Context, folderId string, opts *WorkflowsListOptions) (*schemas.Workflows, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/workflows")
	req = gantryruntime.WithQuery(req, "folder_id", folderId)
	if opts != nil {
		if opts.TriggerType != nil {
			req = gantryruntime.WithQuery(req, "trigger_type", (*opts.TriggerType))
		}
		if opts.Limit != nil {
			req = gantryruntime.WithQuery(req, "limit", strconv.FormatInt((*opts.Limit), 10))
		}
		if opts.Marker != nil {
			req = gantryruntime.WithQuery(req, "marker", (*opts.Marker))
		}
	}
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.Workflows)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *WorkflowsManager) List(ctx context.Context, folderId string, opts *WorkflowsListOptions) iter.Seq2[*schemas.Workflow, error] {
	return func(yield func(*schemas.Workflow, error) bool) {
		var o WorkflowsListOptions
		if opts != nil {
			o = *opts
		}
		for {
			page, err := m.listPage(ctx, folderId, &o)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range page.Entries {
				if !yield(&page.Entries[i], nil) {
					return
				}
			}
			if page.NextMarker == nil || !page.NextMarker.Valid {
				return
			}
			cursor := page.NextMarker.Value
			if cursor == "" {
				return
			}
			next := cursor
			o.Marker = &next
		}
	}
}

func (m *WorkflowsManager) Start(ctx context.Context, workflowId string, body *schemas.WorkflowStartRequest) error {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/workflows"+"/"+url.PathEscape(workflowId)+"/start")
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
