// Code generated by box-gantry 0.1.0. DO NOT EDIT.
package managers

import (
	"context"
	"encoding/json"
	"github.com/unofficialbox/box-open-go-sdk/gantryruntime"
	"github.com/unofficialbox/box-open-go-sdk/schemas"
	"io"
	"net/url"
)

// ZipDownloadsManager groups the "zip_downloads" operations.
type ZipDownloadsManager struct {
	session *gantryruntime.Client
}

// NewZipDownloadsManager builds the manager against a runtime session.
func NewZipDownloadsManager(session *gantryruntime.Client) *ZipDownloadsManager {
	return &ZipDownloadsManager{session: session}
}

func (m *ZipDownloadsManager) Create(ctx context.Context, body *schemas.ZipDownloadRequest) (*schemas.ZipDownload, error) {
	req := m.session.NewRequest("POST", m.session.BaseUrl("api")+"/zip_downloads")
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	req = gantryruntime.WithJsonBody(req, payload)
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ZipDownload)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (m *ZipDownloadsManager) GetContent(ctx context.Context, zipDownloadId string) (io.Reader, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("download")+"/zip_downloads"+"/"+url.PathEscape(zipDownloadId)+"/content")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	return gantryruntime.ResponseStream(resp), nil
}

func (m *ZipDownloadsManager) GetStatus(ctx context.Context, zipDownloadId string) (*schemas.ZipDownloadStatus, error) {
	req := m.session.NewRequest("GET", m.session.BaseUrl("api")+"/zip_downloads"+"/"+url.PathEscape(zipDownloadId)+"/status")
	resp, err := m.session.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}
	data, err := gantryruntime.ResponseBytes(resp)
	if err != nil {
		return nil, err
	}
	out := new(schemas.ZipDownloadStatus)
	if err := json.Unmarshal(data, out); err != nil {
		return nil, err
	}
	return out, nil
}
