// Code generated by box-gantry 0.1.0. DO NOT EDIT.

// Package buildinfo records the provenance of this generated SDK
// (NF-7): the engine version and the fingerprint of the Box
// OpenAPI specs it was generated from.
package buildinfo

const (
	// EngineVersion is the box-gantry version that produced this SDK.
	EngineVersion = "0.1.0"

	// SpecFingerprint identifies the exact input spec set.
	SpecFingerprint = "ee7d55aedefe2fa0"
)
