// Code generated by box-gantry. DO NOT EDIT.
package schemas

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestAiAgentRoundTrip(t *testing.T) {
	var known AiAgent
	if err := json.Unmarshal([]byte(`{"type":"ai_agent_ask"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.AiAgentAsk == nil {
		t.Fatalf("discriminator ai_agent_ask did not select the AiAgentAsk variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "ai_agent_ask") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiAgent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiAgentAllowedEntityRoundTrip(t *testing.T) {
	var known AiAgentAllowedEntity
	if err := json.Unmarshal([]byte(`{"type":"user"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.User == nil {
		t.Fatalf("discriminator user did not select the User variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "user") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiAgentAllowedEntity
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiAskAgentRoundTrip(t *testing.T) {
	var known AiAskAgent
	if err := json.Unmarshal([]byte(`{"type":"ai_agent_id"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.AiAgentId == nil {
		t.Fatalf("discriminator ai_agent_id did not select the AiAgentId variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "ai_agent_id") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiAskAgent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiExtractAgentRoundTrip(t *testing.T) {
	var known AiExtractAgent
	if err := json.Unmarshal([]byte(`{"type":"ai_agent_id"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.AiAgentId == nil {
		t.Fatalf("discriminator ai_agent_id did not select the AiAgentId variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "ai_agent_id") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiExtractAgent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiExtractStructuredAgentRoundTrip(t *testing.T) {
	var known AiExtractStructuredAgent
	if err := json.Unmarshal([]byte(`{"type":"ai_agent_id"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.AiAgentId == nil {
		t.Fatalf("discriminator ai_agent_id did not select the AiAgentId variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "ai_agent_id") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiExtractStructuredAgent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiLlmEndpointParamsRoundTrip(t *testing.T) {
	var known AiLlmEndpointParams
	if err := json.Unmarshal([]byte(`{"type":"openai_params"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.OpenaiParams == nil {
		t.Fatalf("discriminator openai_params did not select the OpenaiParams variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "openai_params") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiLlmEndpointParams
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiTaxonomySourceRoundTrip(t *testing.T) {
	var known AiTaxonomySource
	if err := json.Unmarshal([]byte(`{"type":"taxonomy"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.Taxonomy == nil {
		t.Fatalf("discriminator taxonomy did not select the Taxonomy variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "taxonomy") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiTaxonomySource
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAiTextGenAgentRoundTrip(t *testing.T) {
	var known AiTextGenAgent
	if err := json.Unmarshal([]byte(`{"type":"ai_agent_id"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.AiAgentId == nil {
		t.Fatalf("discriminator ai_agent_id did not select the AiAgentId variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "ai_agent_id") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AiTextGenAgent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestAppItemAssociatedItemRoundTrip(t *testing.T) {
	var known AppItemAssociatedItem
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown AppItemAssociatedItem
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestCollaborationAccessGranteeRoundTrip(t *testing.T) {
	var known CollaborationAccessGrantee
	if err := json.Unmarshal([]byte(`{"type":"user"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.User == nil {
		t.Fatalf("discriminator user did not select the User variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "user") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown CollaborationAccessGrantee
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestCollaborationItemRoundTrip(t *testing.T) {
	var known CollaborationItem
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown CollaborationItem
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestItemRoundTrip(t *testing.T) {
	var known Item
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown Item
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestMetadataQueryResultItemRoundTrip(t *testing.T) {
	var known MetadataQueryResultItem
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown MetadataQueryResultItem
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestRecentItemResourceRoundTrip(t *testing.T) {
	var known RecentItemResource
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown RecentItemResource
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestResourceRoundTrip(t *testing.T) {
	var known Resource
	if err := json.Unmarshal([]byte(`{"type":"folder"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.Folder == nil {
		t.Fatalf("discriminator folder did not select the Folder variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "folder") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown Resource
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestSearchResultItemRoundTrip(t *testing.T) {
	var known SearchResultItem
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown SearchResultItem
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestSearchResultsResponseRoundTrip(t *testing.T) {
	var known SearchResultsResponse
	if err := json.Unmarshal([]byte(`{"type":"search_results_items"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.SearchResultsItems == nil {
		t.Fatalf("discriminator search_results_items did not select the SearchResultsItems variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "search_results_items") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown SearchResultsResponse
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestSearchResultWithSharedLinkItemRoundTrip(t *testing.T) {
	var known SearchResultWithSharedLinkItem
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown SearchResultWithSharedLinkItem
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestHubAccessGranteeRoundTrip(t *testing.T) {
	var known HubAccessGrantee
	if err := json.Unmarshal([]byte(`{"type":"user"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.User == nil {
		t.Fatalf("discriminator user did not select the User variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "user") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown HubAccessGrantee
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestHubDocumentBlockEntryRoundTrip(t *testing.T) {
	var known HubDocumentBlockEntry
	if err := json.Unmarshal([]byte(`{"type":"paragraph"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.Paragraph == nil {
		t.Fatalf("discriminator paragraph did not select the Paragraph variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "paragraph") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown HubDocumentBlockEntry
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestHubItemReferenceRoundTrip(t *testing.T) {
	var known HubItemReference
	if err := json.Unmarshal([]byte(`{"type":"file"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.File == nil {
		t.Fatalf("discriminator file did not select the File variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "file") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown HubItemReference
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestShieldListContentRoundTrip(t *testing.T) {
	var known ShieldListContent
	if err := json.Unmarshal([]byte(`{"type":"country"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.Country == nil {
		t.Fatalf("discriminator country did not select the Country variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "country") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown ShieldListContent
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}

func TestShieldListContentRequestRoundTrip(t *testing.T) {
	var known ShieldListContentRequest
	if err := json.Unmarshal([]byte(`{"type":"country"}`), &known); err != nil {
		t.Fatalf("unmarshal known: %v", err)
	}
	if known.Country == nil {
		t.Fatalf("discriminator country did not select the Country variant")
	}
	out, err := json.Marshal(known)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(out), "country") {
		t.Fatalf("re-marshal dropped the discriminator: %s", out)
	}

	var unknown ShieldListContentRequest
	if err := json.Unmarshal([]byte(`{"type":"__gantry_unknown__"}`), &unknown); err != nil {
		t.Fatalf("unmarshal unknown: %v", err)
	}
	if unknown.Unknown == nil {
		t.Fatalf("unknown discriminator was not retained")
	}
}
